import type { Character } from "./types";

/**
 * ---------------------------------------------------------------------------
 * CHARACTER POOL
 * ---------------------------------------------------------------------------
 * This file is pure data. The engine never switches on a specific character id,
 * so a pool can be swapped, extended or replaced entirely (Marvel, DC, animals,
 * anime, video games ...) without touching game logic. Only two rules matter:
 *
 *   1. Every character must carry the five gameplay stats.
 *   2. `tags` drive map and event modifiers. Unknown tags are ignored, so you
 *      can invent new ones freely and add matching maps/events later.
 *
 * The starter pool is a set of ORIGINAL action-movie-flavoured characters —
 * archetype homages rather than copies of existing characters. If you want to
 * rename them to the characters you had in mind, edit `name`/`title` here only;
 * nothing else in the codebase depends on the names. After editing, run
 * `npm run seed:sql` to regenerate the SQL seed and re-run the migration.
 *
 * BALANCE NOTE: the stat sums are deliberately kept inside a narrow 442–451
 * band so that no single character dominates. Characters differ by shape
 * (glass cannon vs. tank vs. tactician), not by raw total.
 * The numbers are gameplay values only — they are not claims about anybody.
 */

export const CHARACTERS: Character[] = [
  {
    id: "kane-vasco",
    name: "Kane Vasco",
    title: "The Ronin",
    universe: "ACTION",
    rarity: "LEGENDARY",
    power: 88,
    speed: 91,
    defense: 82,
    tactics: 96,
    special: 94,
    specialAbility: "Pencil Work",
    tags: ["melee", "marksman", "tactical", "stealth"],
    basePrice: 10,
    palette: ["#7c3aed", "#22d3ee"],
  },
  {
    id: "adam-kessler",
    name: "Adam Kessler",
    title: "The Erased Asset",
    universe: "ACTION",
    rarity: "LEGENDARY",
    power: 82,
    speed: 90,
    defense: 84,
    tactics: 98,
    special: 92,
    specialAbility: "Improvised Counter",
    tags: ["tactical", "stealth", "brawler", "survival"],
    basePrice: 10,
    palette: ["#2563eb", "#38bdf8"],
  },
  {
    id: "ryder-cross",
    name: "Ryder Cross",
    title: "Impossible Odds",
    universe: "ACTION",
    rarity: "EPIC",
    power: 84,
    speed: 93,
    defense: 80,
    tactics: 94,
    special: 95,
    specialAbility: "Rooftop Gambit",
    tags: ["mobility", "tactical", "tech"],
    basePrice: 9,
    palette: ["#f43f5e", "#fb923c"],
  },
  {
    id: "sterling-vane",
    name: "Sterling Vane",
    title: "Crown Agent",
    universe: "ACTION",
    rarity: "EPIC",
    power: 83,
    speed: 86,
    defense: 85,
    tactics: 97,
    special: 93,
    specialAbility: "Gadget Play",
    tags: ["tactical", "marksman", "tech", "stealth"],
    basePrice: 9,
    palette: ["#0ea5e9", "#a78bfa"],
  },
  {
    id: "tyler-stone",
    name: "Tyler Stone",
    title: "The Extractor",
    universe: "ACTION",
    rarity: "EPIC",
    power: 94,
    speed: 85,
    defense: 92,
    tactics: 82,
    special: 90,
    specialAbility: "One-Shot Corridor",
    tags: ["melee", "ranged", "survival", "brawler"],
    basePrice: 9,
    palette: ["#16a34a", "#84cc16"],
  },
  {
    id: "boone-halloway",
    name: "Boone Halloway",
    title: "The Last Veteran",
    universe: "ACTION",
    rarity: "EPIC",
    power: 95,
    speed: 80,
    defense: 95,
    tactics: 86,
    special: 88,
    specialAbility: "Trap Line",
    tags: ["survival", "ranged", "melee", "veteran"],
    basePrice: 9,
    palette: ["#65a30d", "#facc15"],
  },
  {
    id: "frank-mercer",
    name: "Frank Mercer",
    title: "The Courier",
    universe: "ACTION",
    rarity: "RARE",
    power: 86,
    speed: 92,
    defense: 86,
    tactics: 90,
    special: 89,
    specialAbility: "Precision Delivery",
    tags: ["mobility", "melee", "tactical"],
    basePrice: 8,
    palette: ["#111827", "#f59e0b"],
  },
  {
    id: "elias-quinn",
    name: "Elias Quinn",
    title: "The Bookkeeper",
    universe: "ACTION",
    rarity: "EPIC",
    power: 87,
    speed: 82,
    defense: 90,
    tactics: 97,
    special: 88,
    specialAbility: "Twenty-Nine Seconds",
    tags: ["tactical", "melee", "stealth"],
    basePrice: 9,
    palette: ["#334155", "#22d3ee"],
  },
  {
    id: "bryce-kellan",
    name: "Bryce Kellan",
    title: "The Retriever",
    universe: "ACTION",
    rarity: "RARE",
    power: 89,
    speed: 84,
    defense: 88,
    tactics: 95,
    special: 86,
    specialAbility: "Particular Skills",
    tags: ["tactical", "marksman", "veteran"],
    basePrice: 8,
    palette: ["#7f1d1d", "#f87171"],
  },
  {
    id: "kiri-amano",
    name: "Kiri Amano",
    title: "The Vowed Blade",
    universe: "ACTION",
    rarity: "LEGENDARY",
    power: 88,
    speed: 95,
    defense: 78,
    tactics: 90,
    special: 93,
    specialAbility: "Five Point Strike",
    tags: ["melee", "mobility", "stealth"],
    basePrice: 10,
    palette: ["#fbbf24", "#ef4444"],
  },
  {
    id: "arka-wijaya",
    name: "Arka Wijaya",
    title: "Raid Fist",
    universe: "ACTION",
    rarity: "EPIC",
    power: 92,
    speed: 96,
    defense: 82,
    tactics: 80,
    special: 93,
    specialAbility: "Stairwell Rush",
    tags: ["melee", "brawler", "mobility"],
    basePrice: 9,
    palette: ["#dc2626", "#fde047"],
  },
  {
    id: "cutter-braddock",
    name: "Cutter Braddock",
    title: "Jungle Command",
    universe: "ACTION",
    rarity: "RARE",
    power: 96,
    speed: 78,
    defense: 94,
    tactics: 84,
    special: 90,
    specialAbility: "Suppressing Fire",
    tags: ["ranged", "survival", "leader", "brawler"],
    basePrice: 8,
    palette: ["#166534", "#a3e635"],
  },
  {
    id: "cole-mateo",
    name: "Cole Mateo",
    title: "One Man Squad",
    universe: "ACTION",
    rarity: "RARE",
    power: 98,
    speed: 80,
    defense: 95,
    tactics: 78,
    special: 91,
    specialAbility: "Armory Dump",
    tags: ["brawler", "ranged", "melee"],
    basePrice: 8,
    palette: ["#b45309", "#fbbf24"],
  },
  {
    id: "milo-reyes",
    name: "Milo Reyes",
    title: "The Cleaner",
    universe: "ACTION",
    rarity: "EPIC",
    power: 80,
    speed: 86,
    defense: 82,
    tactics: 98,
    special: 96,
    specialAbility: "Silent Setup",
    tags: ["marksman", "stealth", "tactical"],
    basePrice: 9,
    palette: ["#1e293b", "#4ade80"],
  },
  {
    id: "nash-riggs",
    name: "Nash Riggs",
    title: "Adrenaline Case",
    universe: "ACTION",
    rarity: "RARE",
    power: 93,
    speed: 97,
    defense: 74,
    tactics: 80,
    special: 98,
    specialAbility: "Redline",
    tags: ["mobility", "brawler", "melee"],
    basePrice: 8,
    palette: ["#e11d48", "#f97316"],
  },
  {
    id: "rook-calloway",
    name: "Rook Calloway",
    title: "The Escapist",
    universe: "ACTION",
    rarity: "RARE",
    power: 90,
    speed: 83,
    defense: 88,
    tactics: 92,
    special: 89,
    specialAbility: "Countdown Bluff",
    tags: ["stealth", "survival", "ranged", "leader"],
    basePrice: 8,
    palette: ["#0f172a", "#38bdf8"],
  },
  {
    id: "lin-bo",
    name: "Master Lin Bo",
    title: "Improvised Master",
    universe: "ACTION",
    rarity: "EPIC",
    power: 84,
    speed: 94,
    defense: 84,
    tactics: 92,
    special: 89,
    specialAbility: "Environmental Combat",
    tags: ["melee", "mobility", "brawler", "environment"],
    basePrice: 9,
    palette: ["#f59e0b", "#ef4444"],
  },
  {
    id: "wei-zhan",
    name: "Wei Zhan",
    title: "Iron Discipline",
    universe: "ACTION",
    rarity: "RARE",
    power: 91,
    speed: 93,
    defense: 86,
    tactics: 86,
    special: 87,
    specialAbility: "Wing Chun Chain",
    tags: ["melee", "brawler", "mobility"],
    basePrice: 8,
    palette: ["#1d4ed8", "#f8fafc"],
  },
  {
    id: "dex-harlow",
    name: "Dex Harlow",
    title: "The Mechanic",
    universe: "ACTION",
    rarity: "RARE",
    power: 92,
    speed: 88,
    defense: 89,
    tactics: 85,
    special: 88,
    specialAbility: "Clean Exit",
    tags: ["brawler", "mobility", "melee", "ranged"],
    basePrice: 8,
    palette: ["#475569", "#f43f5e"],
  },
  {
    id: "viktor-sable",
    name: "Viktor Sable",
    title: "The Undisputed",
    universe: "ACTION",
    rarity: "RARE",
    power: 93,
    speed: 95,
    defense: 85,
    tactics: 80,
    special: 89,
    specialAbility: "Spinning Finish",
    tags: ["melee", "mobility", "brawler"],
    basePrice: 8,
    palette: ["#6d28d9", "#f472b6"],
  },
];

export const CHARACTERS_BY_ID: Record<string, Character> = Object.fromEntries(
  CHARACTERS.map((c) => [c.id, c]),
);

/** Single scalar used for ordering, pricing hints and battle ratings. */
export function overall(c: {
  power: number;
  speed: number;
  defense: number;
  tactics: number;
  special: number;
}): number {
  return Math.round(
    (c.power + c.speed + c.defense + c.tactics + c.special) / 5,
  );
}

export function statTotal(c: {
  power: number;
  speed: number;
  defense: number;
  tactics: number;
  special: number;
}): number {
  return c.power + c.speed + c.defense + c.tactics + c.special;
}
