import type { PoolEntry } from "../types";

/**
 * ACTION MOVIES — stats in order: combat, speed, weapons, tactics, durability, special.
 *
 * IP-free archetypes. Original character IDs are unchanged in the database;
 * only names, titles, abilities, universe labels and the `a` (actor) field have
 * been replaced / removed. All entries carry w:null.
 * Game ratings are invented for DRAFT WAR, not an official ranking.
 */
export const ACTION_MOVIES: PoolEntry[] = [
  { n: "The Grief-Driven Cleaner",  w: null, u: "Action", t: "He has a method and the method is flawless because the grief is bottomless.",         g: ["assassin","revenge","marksman","melee"],      s: [94,88,96,84,82,94], ab: ["Close-Range Gunwork","Improvised Strike"],   va: "humanoid_medium", i: { head:"PLAIN", back:"NONE",  marking:"PLAIN",  build:"NORMAL",   prop:"NONE",  scale:1.00 } },
  { n: "The Erased Asset",          w: null, u: "Action", t: "He woke up without a name and built one from what the mirror showed.",                 g: ["spy","stealth","tactical","melee"],           s: [92,86,82,96,82,88], ab: ["Improvised Counter","Countersurveillance"],  va: "humanoid_medium", i: { head:"PLAIN", back:"SHELL", marking:"PLAIN",  build:"NORMAL",   prop:"NONE",  scale:0.97 } },
  { n: "The Impossible Specialist", w: null, u: "Action", t: "He reads the scenario and finds the path no one else could see.",                      g: ["spy","mobility","tactical"],                  s: [86,90,82,94,78,92], ab: ["High-Risk Ascent","Concealed Switch"],      va: "humanoid_medium", i: { head:"PLAIN", back:"CAPE",  marking:"PLAIN",  build:"NORMAL",   prop:"NONE",  scale:0.99 } },
  { n: "The Licensed Operative",    w: null, u: "Action", t: "He has a number, a mandate, and enough field experience to improvise both.",           g: ["spy","marksman","tactical"],                  s: [86,82,90,92,80,88], ab: ["Service Pistol","Field Gadget"],            va: "humanoid_medium", i: { head:"PLAIN", back:"NONE",  marking:"PLAIN",  build:"NORMAL",   prop:"BLADE", scale:1.01 } },
  { n: "The Expendable Contractor", w: null, u: "Action", t: "He is sent in when the situation is already past saving. He saves it anyway.",         g: ["military","survival","melee","brawler"],      s: [90,82,88,76,92,84], ab: ["Corridor Clear","Take the Hit"],            va: "humanoid_large",  i: { head:"PLAIN", back:"NONE",  marking:"PLAIN",  build:"HEAVY",    prop:"NONE",  scale:1.08 } },
  { n: "The Hardened Veteran",      w: null, u: "Action", t: "He survived everything the enemy could think of and came back with more.",              g: ["military","survival","ranged","veteran"],     s: [88,76,92,82,94,86], ab: ["Trap Line","Compound Bow"],                 va: "humanoid_large",  i: { head:"PLAIN", back:"SPINES",marking:"PLAIN",  build:"HEAVY",    prop:"NONE",  scale:1.06 } },
  { n: "The Delivery Specialist",   w: null, u: "Action", t: "Three rules. He broke every one once and learned exactly why they existed.",            g: ["martial-arts","mobility","melee"],            s: [86,84,72,80,78,80], ab: ["Environment Leverage","Precision Driving"],  va: "humanoid_medium", i: { head:"PLAIN", back:"NONE",  marking:"PLAIN",  build:"SLIGHT",   prop:"NONE",  scale:0.96 } },
  { n: "The Measured Avenger",      w: null, u: "Action", t: "He counts the seconds before he acts because he already knows the result.",             g: ["assassin","tactical","melee","stealth"],      s: [92,76,84,96,82,90], ab: ["Improvised Arsenal","Timed Precision"],      va: "humanoid_medium", i: { head:"PLAIN", back:"SPINES",marking:"PLAIN",  build:"NORMAL",   prop:"NONE",  scale:1.02 } },
  { n: "The Desperate Rescuer",     w: null, u: "Action", t: "He has a very particular set of skills and a very particular target.",                  g: ["spy","revenge","tactical","marksman"],        s: [82,70,82,90,76,76], ab: ["Signal Lock","Interrogation"],              va: "humanoid_medium", i: { head:"PLAIN", back:"FIN",   marking:"PLAIN",  build:"NORMAL",   prop:"NONE",  scale:1.01 } },
  { n: "The Trained Avenger",       w: null, u: "Action", t: "She was trained to be perfect. She used it to settle a debt.",                         g: ["assassin","revenge","martial-arts","melee"],  s: [90,84,80,78,80,88], ab: ["Master Blade","Pressure Point Strike"],     va: "humanoid_medium", i: { head:"PLAIN", back:"NONE",  marking:"PLAIN",  build:"SLIGHT",   prop:"BLADE", scale:0.97 } },
  { n: "The Corridor Fighter",      w: null, u: "Action", t: "One floor at a time. He has never needed more of a plan than that.",                   g: ["martial-arts","military","melee","mobility"], s: [96,92,66,74,84,90], ab: ["Silat Chain","Stairwell Rush"],             va: "humanoid_medium", i: { head:"PLAIN", back:"SHELL", marking:"PLAIN",  build:"SLIGHT",   prop:"NONE",  scale:0.95 } },
  { n: "The Jungle Commander",      w: null, u: "Action", t: "He has never lost a man he did not eventually avenge.",                                g: ["military","survival","leader","ranged"],      s: [78,64,88,82,86,76], ab: ["Thermal Mask","Suppressing Fire"],          va: "humanoid_large",  i: { head:"PLAIN", back:"SHELL", marking:"PLAIN",  build:"TOWERING", prop:"NONE",  scale:1.16 } },
  { n: "The One-Man Arsenal",       w: null, u: "Action", t: "He carries more than he needs and uses all of it.",                                    g: ["military","brawler","ranged","revenge"],      s: [80,62,90,70,88,74], ab: ["Equipment Sweep","Chokehold Breach"],       va: "humanoid_large",  i: { head:"PLAIN", back:"NONE",  marking:"PLAIN",  build:"TOWERING", prop:"NONE",  scale:1.14 } },
  { n: "The Silent Cleaner",        w: null, u: "Action", t: "He is in and out before the building knows there was a problem.",                      g: ["assassin","stealth","marksman","tactical"],   s: [86,78,94,92,74,90], ab: ["Silent Setup","Room Sweep"],                va: "humanoid_medium", i: { head:"PLAIN", back:"MANE",  marking:"PLAIN",  build:"NORMAL",   prop:"NONE",  scale:0.99 } },
  { n: "The Burning Engine",        w: null, u: "Action", t: "He cannot slow down. He has turned this into a strategy.",                             g: ["brawler","mobility","melee"],                 s: [82,90,72,62,76,92], ab: ["Adrenaline Spike","Redline"],               va: "humanoid_medium", i: { head:"PLAIN", back:"CAPE",  marking:"PLAIN",  build:"SLIGHT",   prop:"NONE",  scale:0.94 } },
  { n: "The Presumed Dead",         w: null, u: "Action", t: "He has been declared finished too many times to take it personally.",                  g: ["survival","stealth","ranged","revenge"],      s: [78,70,84,86,78,80], ab: ["Leverage Play","Glider Entry"],             va: "humanoid_medium", i: { head:"PLAIN", back:"SPINES",marking:"PLAIN",  build:"NORMAL",   prop:"BLADE", scale:0.98 } },
  { n: "The Endurance Soldier",     w: null, u: "Action", t: "She has run out of ammunition, allies, and options. She has not run out of resolve.",  g: ["survival","tactical","ranged","military"],    s: [66,66,82,92,80,84], ab: ["Exo-Rig","Vacuum Expulsion"],               va: "humanoid_medium", i: { head:"PLAIN", back:"SHELL", marking:"PLAIN",  build:"SQUAT",    prop:"NONE",  scale:0.98 } },
  { n: "The Future Soldier",        w: null, u: "Action", t: "She builds against a war that has not happened yet. She does not stop.",               g: ["survival","military","ranged","tactical"],    s: [72,70,84,86,78,76], ab: ["Prepper Cache","Shotgun Reload"],           va: "humanoid_medium", i: { head:"PLAIN", back:"MANE",  marking:"PLAIN",  build:"NORMAL",   prop:"BLADE", scale:0.96 } },
  { n: "The Reluctant Hero",        w: null, u: "Action", t: "He did not volunteer. He was just the only one who could do it.",                      g: ["survival","tactical","brawler","marksman"],   s: [78,70,84,92,90,86], ab: ["Barefoot Escape","Vent Crawl"],             va: "humanoid_medium", i: { head:"PLAIN", back:"CAPE",  marking:"PLAIN",  build:"NORMAL",   prop:"BLADE", scale:1.00 } },
  { n: "The Edge Walker",           w: null, u: "Action", t: "He fights like he has nothing left to lose, which makes him genuinely dangerous.",     g: ["martial-arts","marksman","melee"],            s: [84,78,84,72,78,78], ab: ["Jujitsu Lock","Trick Shot"],                va: "humanoid_medium", i: { head:"PLAIN", back:"SPINES",marking:"PLAIN",  build:"SLIGHT",   prop:"BLADE", scale:0.97 } },
  { n: "The Rewritten One",         w: null, u: "Action", t: "He found the edge of the possible and walked through it.",                             g: ["martial-arts","mobility","melee"],            s: [92,96,78,82,88,98], ab: ["Temporal Dodge","Reality Override"],        va: "humanoid_medium", i: { head:"PLAIN", back:"SHELL", marking:"PLAIN",  build:"NORMAL",   prop:"BLADE", scale:1.02 } },
  { n: "The Precise Infiltrator",   w: null, u: "Action", t: "She gets in, takes the shot, and is gone before the sound arrives.",                   g: ["martial-arts","mobility","marksman","stealth"],s: [82,88,84,80,70,84], ab: ["Wire Kick","Dual Pistols"],                 va: "humanoid_medium", i: { head:"PLAIN", back:"SPINES",marking:"PLAIN",  build:"SLIGHT",   prop:"NONE",  scale:0.94 } },
  { n: "The Wasteland Driver",      w: null, u: "Action", t: "He is not looking for a destination. He is looking for a direction worth moving in.",  g: ["survival","mobility","brawler"],              s: [78,76,78,78,86,78], ab: ["Vehicle Fight","Fuel Run"],                 va: "humanoid_medium", i: { head:"PLAIN", back:"NONE",  marking:"PLAIN",  build:"HEAVY",    prop:"NONE",  scale:1.02 } },
  { n: "The One-Armed Vanguard",    w: null, u: "Action", t: "She leads because the alternative is worse, and she is very good at making that point.", g: ["survival","military","leader","ranged"],      s: [82,76,84,86,80,80], ab: ["Armored Convoy","One Arm Shot"],            va: "humanoid_medium", i: { head:"PLAIN", back:"FIN",   marking:"PLAIN",  build:"NORMAL",   prop:"BLADE", scale:0.98 } },
  { n: "The Enduring Machine",      w: null, u: "Action", t: "He does not feel pain, negotiate, or stop. That is the entire problem.",               g: ["military","survival","ranged","brawler"],     s: [86,68,92,78,98,88], ab: ["Inner Frame","Target Lock"],                va: "humanoid_large",  i: { head:"PLAIN", back:"SPINES",marking:"STRIPES",  build:"TOWERING", prop:"NONE",  scale:1.16 } },
  { n: "The Daywalking Hunter",     w: null, u: "Action", t: "He is the thing in the dark that hunts the other things in the dark.",                 g: ["martial-arts","assassin","melee","revenge"],  s: [88,84,82,74,84,88], ab: ["Silver Blade","Glaive Throw"],              va: "humanoid_medium", i: { head:"PLAIN", back:"CAPE",  marking:"PLAIN",  build:"SLIGHT",   prop:"BLADE", scale:0.96 } },
  { n: "The Night-Eyed Fugitive",   w: null, u: "Action", t: "He sees in the dark. The dark has never recovered from the disadvantage.",             g: ["survival","stealth","brawler","melee"],       s: [86,78,74,80,86,88], ab: ["Night Sight","Ambush Strike"],              va: "humanoid_medium", i: { head:"PLAIN", back:"FIN",   marking:"PLAIN",  build:"SLIGHT",   prop:"NONE",  scale:0.98 } },
  { n: "The Remade Operative",      w: null, u: "Action", t: "She was built into something lethal. That was their mistake.",                         g: ["assassin","spy","stealth","marksman"],        s: [80,80,82,80,68,80], ab: ["Cover Identity","Emergency Exit"],          va: "humanoid_medium", i: { head:"PLAIN", back:"MANE",  marking:"PLAIN",  build:"SLIGHT",   prop:"NONE",  scale:0.93 } },
  { n: "The Double Agent",          w: null, u: "Action", t: "She is never exactly who you think she is, and she has made that her entire skill set.", g: ["spy","stealth","mobility","tactical"],        s: [80,84,76,86,72,82], ab: ["Improvised Chemistry","Truck Leap"],        va: "humanoid_medium", i: { head:"PLAIN", back:"SHELL", marking:"PLAIN",  build:"SLIGHT",   prop:"BLADE", scale:0.95 } },
  { n: "The Cold War Agent",        w: null, u: "Action", t: "She operates in the grey area between nations and has written the map of it.",          g: ["spy","martial-arts","melee","stealth"],       s: [88,78,76,84,80,82], ab: ["Stairwell Fight","Cable Choke"],            va: "humanoid_medium", i: { head:"PLAIN", back:"MANE",  marking:"PLAIN",  build:"SLIGHT",   prop:"BLADE", scale:0.97 } },
];
