import type { PoolEntry } from "../types";

/**
 * ANIME — stats in order: power, speed, durability, combat, intelligence, special.
 *
 * IP-free archetypes. Original character IDs are unchanged in the database;
 * only names, titles, abilities and universe labels have been replaced.
 * All entries carry w:null so the wiki-enrich script never overwrites them.
 * Game ratings are invented for DRAFT WAR, not an official ranking.
 */
export const ANIME: PoolEntry[] = [
  { n: "The Boundless Paragon",   w: null, u: "Anime", t: "He hits the ceiling and immediately builds a new one.",                               g: ["martial-arts","melee","brawler"],          s: [98,96,92,96,62,94],  ab: ["Ascendant Surge","Limitless Threshold"],    va: "humanoid_large",  i: { head:"PLAIN", back:"NONE",  marking:"PLAIN",   build:"TOWERING", prop:"NONE",  scale:1.14 } },
  { n: "The Crowned Rival",       w: null, u: "Anime", t: "Second place is not a rank he recognises.",                                           g: ["martial-arts","melee","villain"],          s: [95,92,90,94,76,90],  ab: ["Royal Volley","Surge of Pride"],            va: "humanoid_large",  i: { head:"PLAIN", back:"NONE",  marking:"PLAIN",   build:"HEAVY",    prop:"NONE",  scale:1.06 } },
  { n: "The Gilded Emperor",      w: null, u: "Anime", t: "His cruelty is precise and his smile is genuine.",                                    g: ["villain"],                                 s: [92,92,86,82,86,90],  ab: ["Precision Ray","Final Form Surge"],                                 i: { head:"PLAIN", back:"NONE",  marking:"PLAIN",   build:"SLIGHT",   prop:"NONE",  scale:0.94 } },
  { n: "The Blazing Outcast",     w: null, u: "Anime", t: "He ran toward the village that used to look away.",                                   g: ["ninja","brawler","leader"],                s: [92,88,88,84,62,94],  ab: ["Clone Swarm","Spiral Force"],                                       i: { head:"PLAIN", back:"NONE",  marking:"PLAIN",   build:"NORMAL",   prop:"HAMMER",scale:1.00 } },
  { n: "The Dark Prodigy",        w: null, u: "Anime", t: "Talent given a grievance is the most dangerous combination.",                         g: ["ninja","swordsman","villain"],             s: [90,90,80,90,86,94],  ab: ["Eye Technique","Black Lightning Arc"],                              i: { head:"PLAIN", back:"NONE",  marking:"PLAIN",   build:"SLIGHT",   prop:"BLADE", scale:0.95 } },
  { n: "The Eternal Warlord",     w: null, u: "Anime", t: "Legends are written about him, not by him.",                                         g: ["ninja","villain","swordsman"],             s: [94,90,88,94,90,96],  ab: ["Warrior's Colossus","Reality Veil"],        va: "humanoid_large",  i: { head:"PLAIN", back:"CAPE",  marking:"PLAIN",   build:"HEAVY",    prop:"BLADE", scale:1.10 } },
  { n: "The Silver Copyist",      w: null, u: "Anime", t: "He has seen every technique once, which is all he needs.",                           g: ["ninja","tactical","stealth"],              s: [76,82,70,88,92,84],  ab: ["Mirror Strike","Pursuit Arc"],                                      i: { head:"PLAIN", back:"NONE",  marking:"PLAIN",   build:"NORMAL",   prop:"BLADE", scale:0.97 } },
  { n: "The Wild Captain",        w: null, u: "Anime", t: "He doesn't calculate the odds — he ignores them and wins.",                          g: ["pirate","brawler","leader"],               s: [92,86,94,86,52,94],  ab: ["Elastic Barrage","Giant Form Strike"],                              i: { head:"PLAIN", back:"SPINES",marking:"PLAIN",   build:"NORMAL",   prop:"NONE",  scale:0.98 } },
  { n: "The Stoic Bladesman",     w: null, u: "Anime", t: "Three swords, one direction, no need to explain further.",                           g: ["pirate","swordsman","melee"],              s: [86,80,88,94,52,86],  ab: ["Three-Edge Assault","Oni Cleave"],                                  i: { head:"PLAIN", back:"NONE",  marking:"PLAIN",   build:"HEAVY",    prop:"BLADE", scale:1.02 } },
  { n: "The Relentless Reaper",   w: null, u: "Anime", t: "He fights for the living because something inside him remembers what that means.",   g: ["swordsman","melee"],                       s: [88,88,82,86,58,90],  ab: ["Black Wave Release","Masked Transformation"],                       i: { head:"PLAIN", back:"SPINES",marking:"PLAIN",   build:"NORMAL",   prop:"BLADE", scale:1.00 } },
  { n: "The Vengeful Titan",      w: null, u: "Anime", t: "Freedom was the word and he rewrote everything around it.",                          g: ["villain","brawler"],                       s: [86,64,88,70,78,88],  ab: ["Giant Shift","Armored Shell"],              va: "humanoid_large",  i: { head:"PLAIN", back:"NONE",  marking:"PLAIN",   build:"TOWERING", prop:"BLADE", scale:1.16 } },
  { n: "The Rapid Blade",         w: null, u: "Anime", t: "Where others swing once, he has already finished.",                                  g: ["swordsman","mobility","tactical"],         s: [58,94,64,96,86,82],  ab: ["Spinning Blade Rush","Controlled Descent"],                         i: { head:"PLAIN", back:"SHELL", marking:"PLAIN",   build:"SLIGHT",   prop:"BLADE", scale:0.90 } },
  { n: "The Absolute Champion",   w: null, u: "Anime", t: "He found the ceiling and was disappointed by it.",                                   g: ["brawler","melee"],                         s: [100,94,96,70,50,92], ab: ["Consecutive Rush","World-Ending Strike"],                            i: { head:"PLAIN", back:"NONE",  marking:"PLAIN",   build:"NORMAL",   prop:"NONE",  scale:0.97 } },
  { n: "The Kind Slayer",         w: null, u: "Anime", t: "He learned to grieve without letting it stop the blade.",                            g: ["swordsman","hunter","melee"],              s: [70,80,72,84,80,82],  ab: ["Flowing Strike Pattern","Sun-Cycle Slash"],                         i: { head:"PLAIN", back:"CAPE",  marking:"PLAIN",   build:"NORMAL",   prop:"BLADE", scale:0.96 } },
  { n: "The Unseen Sovereign",    w: null, u: "Anime", t: "He sees everything because nothing can reach him first.",                            g: ["hunter","tactical"],                       s: [96,94,86,86,92,98],  ab: ["Absolute Barrier","Hollow Convergence"],                            i: { head:"PLAIN", back:"NONE",  marking:"PLAIN",   build:"NORMAL",   prop:"ORB",   scale:1.00 } },
  { n: "The Electric Heir",       w: null, u: "Anime", t: "He was born into the kill and chose something else — for a while.",                  g: ["hunter","assassin","mobility","stealth"],  s: [74,92,66,88,90,86],  ab: ["Lightning Burst","Nerve-Cut Strike"],                               i: { head:"PLAIN", back:"MANE",  marking:"PLAIN",   build:"SLIGHT",   prop:"NONE",  scale:0.89 } },
  { n: "The Bright Hunter",       w: null, u: "Anime", t: "He doesn't have a ceiling because he never thought to look for one.",                g: ["hunter","brawler","melee"],                s: [78,78,76,80,64,86],  ab: ["Impact Throw","Wild Overdrive"],                                    i: { head:"PLAIN", back:"NONE",  marking:"PLAIN",   build:"SQUAT",    prop:"NONE",  scale:0.94 } },
  { n: "The Crimson Jester",      w: null, u: "Anime", t: "He is not hunting you specifically — you just happened to be interesting.",          g: ["hunter","villain","tactical"],             s: [76,84,72,90,92,90],  ab: ["Elastic Snare","Illusory Surface"],                                 i: { head:"PLAIN", back:"FIN",   marking:"STRIPES", build:"NORMAL",   prop:"BLADE", scale:0.97 } },
  { n: "The Forged Alchemist",    w: null, u: "Anime", t: "He traded an arm to learn the hard lesson and immediately used it.",                 g: ["tactical","melee"],                        s: [70,76,72,82,94,86],  ab: ["Matter Reshape","Living Metal Strike"],                             i: { head:"PLAIN", back:"NONE",  marking:"PLAIN",   build:"SQUAT",    prop:"BLADE", scale:0.90 } },
  { n: "The Scarred Berserker",   w: null, u: "Anime", t: "The sword is too big, the enemies too many, and he hasn't stopped yet.",             g: ["swordsman","brawler","melee"],             s: [90,76,94,96,78,88],  ab: ["Colossal Sweep","Rage Armour"],             va: "humanoid_large",  i: { head:"PLAIN", back:"NONE",  marking:"PLAIN",   build:"HEAVY",    prop:"BLADE", scale:1.08 } },
  { n: "The Shining Symbol",      w: null, u: "Anime", t: "He showed up so completely that people forgot what fear felt like.",                 g: ["brawler","leader","melee"],                s: [94,88,88,84,74,88],  ab: ["Overwhelming Smash","Last Stand"],          va: "humanoid_large",  i: { head:"PLAIN", back:"CAPE",  marking:"PLAIN",   build:"TOWERING", prop:"NONE",  scale:1.18 } },
  { n: "The Fractured Duelist",   w: null, u: "Anime", t: "Two powers, one wound, and a choice he keeps making every time.",                   g: ["hunter","ranged"],                         s: [82,74,72,72,80,86],  ab: ["Glacial Pulse","Heat Flare"],                                       i: { head:"PLAIN", back:"SPINES",marking:"STRIPES", build:"NORMAL",   prop:"ORB",   scale:0.97 } },
];
