import type { PoolEntry } from "../types";

/**
 * FANTASY — stats in order: power, speed, durability, combat, magic, special.
 *
 * IP-free archetypes. Original character IDs are unchanged in the database;
 * only names, titles, abilities and universe labels have been replaced.
 * All entries carry w:null so the wiki-enrich script never overwrites them.
 * Game ratings are invented for DRAFT WAR, not an official ranking.
 *
 * Public-domain entries (Merlin, Beowulf, Morgan le Fay) retain their names
 * as the characters themselves are the archetypes. All trademarked ability
 * and universe names have been replaced.
 */
export const FANTASY: PoolEntry[] = [
  { n: "The Wandering Sage",        w: null, u: "Fantasy", t: "He arrives precisely when he needs to and refuses to explain how.",                          g: ["fellowship","mage","leader","tactical"],     s: [88,62,74,78,96,94], ab: ["Staff Light","Word of Command"],         va: "humanoid_medium", i: { head:"PLAIN", back:"CAPE",  marking:"PLAIN",  build:"NORMAL",   prop:"NONE",  scale:1.02 } },
  { n: "The Returning Sovereign",   w: null, u: "Fantasy", t: "He was not on the throne. He was the reason the throne still existed.",                       g: ["fellowship","royal","melee","leader"],       s: [70,76,76,94,30,78], ab: ["Ancestral Blade","Rally the Host"],       va: "humanoid_medium", i: { head:"PLAIN", back:"CAPE",  marking:"PLAIN",  build:"NORMAL",   prop:"BLADE", scale:1.01 } },
  { n: "The Elven Marksman",        w: null, u: "Fantasy", t: "He does not miss. The question is what he is choosing not to hit.",                           g: ["fellowship","marksman","mobility","ranged"], s: [62,92,62,88,34,84], ab: ["Impossible Shot","Rapid Fire"],          va: "humanoid_medium", i: { head:"PLAIN", back:"NONE",  marking:"PLAIN",  build:"SLIGHT",   prop:"BOW",   scale:0.95 } },
  { n: "The Steadfast Axeman",      w: null, u: "Fantasy", t: "He has never retreated in his life and does not intend to start now.",                        g: ["fellowship","brawler","melee","survival"],   s: [78,54,88,86,20,68], ab: ["Axe Cleave","Dwarven Endurance"],        va: "humanoid_medium", i: { head:"PLAIN", back:"NONE",  marking:"PLAIN",  build:"SQUAT",    prop:"BLADE", scale:0.88 } },
  { n: "The Dark Sovereign",        w: null, u: "Fantasy", t: "He did not need an army to end the world. He just needed time.",                              g: ["monster","mage","royal"],                    s: [96,66,94,88,98,96], ab: ["Binding Gaze","Mace Sweep"],             va: "humanoid_large",  i: { head:"PLAIN", back:"SPINES",marking:"PLAIN",  build:"TOWERING", prop:"NONE",  scale:1.16 } },
  { n: "The Fallen Councilor",      w: null, u: "Fantasy", t: "He was the wisest of them, which made what came after so much worse.",                        g: ["mage","leader"],                             s: [82,56,66,62,92,86], ab: ["Persuasive Voice","Storm Call"],          va: "humanoid_medium", i: { head:"PLAIN", back:"NONE",  marking:"PLAIN",  build:"NORMAL",   prop:"NONE",  scale:1.00 } },
  { n: "The Mirror Lady",           w: null, u: "Fantasy", t: "She shows you what you are, not what you want to be. That is the power.",                     g: ["mage","royal"],                              s: [86,62,62,52,96,92], ab: ["Mirror Sight","Radiant Light"],          va: "humanoid_medium", i: { head:"PLAIN", back:"NONE",  marking:"PLAIN",  build:"SLIGHT",   prop:"ORB",   scale:0.96 } },
  { n: "The Wraith Commander",      w: null, u: "Fantasy", t: "He was told he could not be killed by any man. No one asked about the other options.",        g: ["monster","mage","melee"],                    s: [88,72,90,88,84,90], ab: ["Cursed Blade","Fell Beast"],             va: "humanoid_large",  i: { head:"PLAIN", back:"CAPE",  marking:"PLAIN",  build:"HEAVY",    prop:"BLADE", scale:1.08 } },
  { n: "The Ancient Flame",         w: null, u: "Fantasy", t: "He was old when the mountains were young. He is still angry about it.",                       g: ["monster","dragon"],                          s: [96,66,96,82,80,92], ab: ["Flame Whip","Shadow Surge"],             va: "humanoid_large",  i: { head:"PLAIN", back:"MANE",  marking:"PLAIN",  build:"TOWERING", prop:"NONE",  scale:1.18 } },
  { n: "The Final Drake",           w: null, u: "Fantasy", t: "He outlived every hunter who came for him, and they kept coming.",                            g: ["monster","dragon"],                          s: [98,82,96,76,74,96], ab: ["Dragon Fire","Scaled Hide"],             va: "serpentine",      i: { head:"PLAIN", back:"SPINES",marking:"PLAIN",  build:"NORMAL",   prop:"NONE",  scale:1.08 } },
  { n: "The Elven Warden",          w: null, u: "Fantasy", t: "He held the line long enough for everyone else to decide whether to hold theirs.",            g: ["mage","royal","melee"],                      s: [76,74,72,86,84,78], ab: ["Elven Blade","Flood the Ford"],          va: "humanoid_medium", i: { head:"PLAIN", back:"NONE",  marking:"PLAIN",  build:"NORMAL",   prop:"BLADE", scale:1.00 } },
  { n: "The Hidden Warrior",        w: null, u: "Fantasy", t: "She was exactly what they said could not be there, which is how she won.",                    g: ["royal","melee"],                             s: [64,74,68,84,20,88], ab: ["Shieldmaiden's Form","Defy the Prophecy"], va: "humanoid_medium", i: { head:"PLAIN", back:"NONE",  marking:"PLAIN",  build:"SLIGHT",   prop:"BLADE", scale:0.96 } },
  { n: "The Northern Ranger",       w: null, u: "Fantasy", t: "He did not ask for the weight. He carried it anyway.",                                        g: ["royal","melee","leader","survival"],         s: [66,74,74,86,18,74], ab: ["Ancestral Sword","Hold the Wall"],       va: "humanoid_medium", i: { head:"PLAIN", back:"SPINES",marking:"PLAIN",  build:"NORMAL",   prop:"BLADE", scale:0.99 } },
  { n: "The Faceless Blade",        w: null, u: "Fantasy", t: "She has no name until she is standing in front of the person who matters.",                   g: ["stealth","assassin","mobility"],             s: [46,88,52,86,30,92], ab: ["Concealed Identity","Needle Strike"],    va: "humanoid_medium", i: { head:"PLAIN", back:"SHELL", marking:"PLAIN",  build:"SLIGHT",   prop:"BLADE", scale:0.90 } },
  { n: "The Dragon Sovereign",      w: null, u: "Fantasy", t: "She commands fire because she earned the right to.",                                          g: ["royal","dragon","leader"],                   s: [82,52,62,38,72,94], ab: ["Dragon Command","Unburnt"],              va: "humanoid_medium", i: { head:"PLAIN", back:"CAPE",  marking:"PLAIN",  build:"SLIGHT",   prop:"NONE",  scale:0.96 } },
  { n: "The Unstoppable Brute",     w: null, u: "Fantasy", t: "He is not fast. He does not need to be.",                                                     g: ["monster","brawler","melee"],                 s: [92,44,92,84,10,70], ab: ["Greatsword Cleave","Unstoppable March"],  va: "humanoid_large",  i: { head:"PLAIN", back:"NONE",  marking:"PLAIN",  build:"HEAVY",    prop:"BLADE", scale:1.14 } },
  { n: "The Oath Keeper",           w: null, u: "Fantasy", t: "She swore and meant it, which makes her exceptional in the circles she moves in.",            g: ["melee","survival"],                          s: [76,66,82,90,12,70], ab: ["Vow Strike","Guard Stance"],             va: "humanoid_medium", i: { head:"PLAIN", back:"NONE",  marking:"PLAIN",  build:"HEAVY",    prop:"BLADE", scale:1.02 } },
  { n: "The Silver Hunter",         w: null, u: "Fantasy", t: "He was made to kill monsters and never found a reason to stop.",                              g: ["monster","melee","mage","survival"],         s: [78,84,82,94,66,88], ab: ["Igni Sign","Silver Sword"],              va: "humanoid_medium", i: { head:"PLAIN", back:"MANE",  marking:"PLAIN",  build:"NORMAL",   prop:"BLADE", scale:1.00 } },
  { n: "The Chaos Weaver",          w: null, u: "Fantasy", t: "She does not control chaos. She shapes it, which is harder.",                                 g: ["mage"],                                      s: [86,62,58,48,94,90], ab: ["Portal Step","Chaos Bolt"],              va: "humanoid_medium", i: { head:"PLAIN", back:"NONE",  marking:"PLAIN",  build:"SLIGHT",   prop:"NONE",  scale:0.92 } },
  { n: "The Elder Wanderer",        w: null, u: "Fantasy", t: "She moves through possibilities the way others move through rooms.",                          g: ["mage","mobility","melee","royal"],           s: [84,92,68,84,82,96], ab: ["Blink Step","Elder Blood Surge"],        va: "humanoid_medium", i: { head:"PLAIN", back:"SPINES",marking:"PLAIN",  build:"SLIGHT",   prop:"NONE",  scale:0.93 } },
  { n: "Merlin",                    w: null, u: "Fantasy", t: "The first of the art and the last to be believed.",                                           g: ["mage","tactical"],                          s: [84,48,58,46,96,92], ab: ["Prophecy","Binding Spell"],              va: "humanoid_medium", i: { head:"PLAIN", back:"NONE",  marking:"PLAIN",  build:"SQUAT",    prop:"ORB",   scale:0.91 } },
  { n: "The Iron Barbarian",        w: null, u: "Fantasy", t: "Steel and will are the only philosophy he has ever needed.",                                  g: ["melee","brawler","survival"],                s: [86,76,84,92,14,76], ab: ["Iron Grip","Reckless Charge"],           va: "humanoid_medium", i: { head:"PLAIN", back:"MANE",  marking:"PLAIN",  build:"HEAVY",    prop:"BLADE", scale:1.04 } },
  { n: "Beowulf",                   w: null, u: "Fantasy", t: "He went looking for the monster because no one else would.",                                  g: ["melee","brawler","royal"],                   s: [84,68,86,88,16,74], ab: ["Bare Handed","Hero's Grip"],             va: "humanoid_large",  i: { head:"PLAIN", back:"NONE",  marking:"PLAIN",  build:"HEAVY",    prop:"NONE",  scale:1.10 } },
  { n: "Morgan le Fay",             w: null, u: "Fantasy", t: "She works at a distance and the results are always exactly what she intended.",               g: ["mage","royal"],                              s: [80,58,58,46,92,90], ab: ["Glamour","Curse"],                       va: "humanoid_medium", i: { head:"PLAIN", back:"CAPE",  marking:"PLAIN",  build:"SLIGHT",   prop:"ORB",   scale:0.94 } },
];
