import type { PoolEntry } from "../types";

/**
 * FOOTBALL — stats in order: finishing, vision, pace, physical, technique,
 * composure.
 *
 * **These are invented people.** Global football keeps producing the same
 * handful of roles — the tiny playmaker who sees the pass nobody else does,
 * the towering finisher, the wall at the back — and those *roles* are what a
 * table argues about. So the roles are what this pool contains: original
 * characters built to read as an archetype, with no real athlete's name, face,
 * hair, kit, club, badge or celebration anywhere in them. `w: null` on every
 * entry keeps the Wikipedia enricher away from them for the same reason.
 *
 * Nationality words appear as *cultural* shorthand — "The Argentine Maestro"
 * names a style of football, the way "spaghetti western" names a style of
 * film. Palettes take a hint from national colours and stop there: no jersey
 * design, no crest, no sponsor.
 *
 * Every rating is a GAME RATING invented for DRAFT WAR. Nothing here describes
 * a real person, because there is no real person here to describe.
 */
export const FOOTBALL: PoolEntry[] = [
  {
    n: "The Argentine Maestro", w: null, u: "Original", t: "Sees the pass before it exists",
    g: ["playmaker", "technical", "midfielder"],
    s: [84, 98, 70, 42, 97, 92],
    ab: ["Impossible Angle", "Weight of Pass"],
    nick: "THE MAESTRO", va: "humanoid_medium",
    i: { head: "PLAIN", back: "NONE", marking: "PATCH", build: "SLIGHT", prop: "BALL", scale: 0.88 },
  },
  {
    n: "The Portuguese Machine", w: null, u: "Original", t: "Turns space into a weapon",
    g: ["striker", "physical", "speed", "aerial"],
    s: [96, 70, 90, 92, 82, 88],
    ab: ["Hang Time", "Second Effort"],
    nick: "THE MACHINE", va: "humanoid_large",
    i: { head: "PLAIN", back: "NONE", marking: "STRIPES", build: "TOWERING", prop: "BALL", scale: 1.02 },
  },
  {
    n: "The Brazilian Showman", w: null, u: "Original", t: "Beats you, then beats you again",
    g: ["flair", "technical", "speed", "playmaker"],
    s: [80, 88, 88, 58, 97, 66],
    ab: ["Elastico", "Draw the Foul"],
    nick: "THE SHOWMAN", va: "humanoid_medium",
    i: { head: "PLAIN", back: "NONE", marking: "SPOTS", build: "NORMAL", prop: "BALL", scale: 0.96 },
  },
  {
    n: "The French Phenom", w: null, u: "Original", t: "Gone before the defender turns",
    g: ["striker", "speed", "finisher"],
    s: [92, 72, 99, 66, 86, 82],
    ab: ["First Ten Yards", "Cut Inside"],
    nick: "THE PHENOM", va: "humanoid_medium",
    i: { head: "PLAIN", back: "NONE", marking: "STRIPES", build: "SLIGHT", prop: "BALL", scale: 0.94 },
  },
  {
    n: "The Northern Viking", w: null, u: "Original", t: "Arrives like weather",
    g: ["striker", "physical", "finisher", "aerial"],
    s: [95, 62, 84, 97, 70, 86],
    ab: ["Shoulder Charge", "Near Post Run"],
    nick: "THE VIKING", va: "humanoid_large",
    i: { head: "PLAIN", back: "MANE", marking: "PLAIN", build: "TOWERING", prop: "BALL", scale: 1.10 },
  },
  {
    n: "The Spanish Conductor", w: null, u: "Original", t: "Sets the tempo and never loses it",
    g: ["playmaker", "technical", "tactical", "midfielder"],
    s: [62, 96, 58, 44, 94, 95],
    ab: ["Half Turn", "Third Man Run"],
    nick: "THE CONDUCTOR", va: "humanoid_medium",
    i: { head: "PLAIN", back: "NONE", marking: "BANDS", build: "SQUAT", prop: "BALL", scale: 0.90 },
  },
  {
    n: "The German Engine", w: null, u: "Original", t: "Still running in the ninetieth minute",
    g: ["midfielder", "tactical", "physical"],
    s: [76, 92, 82, 82, 80, 90],
    ab: ["Counter Press", "Late Arrival"],
    nick: "THE ENGINE", va: "humanoid_medium",
    i: { head: "PLAIN", back: "NONE", marking: "PLAIN", build: "NORMAL", prop: "BALL", scale: 1.00 },
  },
  {
    n: "The Italian Wall", w: null, u: "Original", t: "Reads the striker's mind, then his feet",
    g: ["defender", "defensive", "physical", "tactical"],
    s: [40, 82, 52, 95, 64, 94],
    ab: ["Anticipation", "Body Between"],
    nick: "THE WALL", va: "humanoid_large",
    i: { head: "HELM", back: "NONE", marking: "PLAIN", build: "HEAVY", prop: "SHIELD", scale: 1.02 },
  },
  {
    n: "The South American Keeper", w: null, u: "Original", t: "The last argument",
    g: ["keeper", "defensive", "tactical"],
    s: [20, 80, 56, 88, 72, 97],
    ab: ["Spread the Frame", "Command the Box"],
    nick: "THE KEEPER", va: "humanoid_large",
    i: { head: "HELM", back: "NONE", marking: "PATCH", build: "HEAVY", prop: "SHIELD", scale: 0.98 },
  },
  {
    n: "The Continental Architect", w: null, u: "Original", t: "Builds the game from the back",
    g: ["playmaker", "tactical", "technical", "midfielder"],
    s: [58, 97, 64, 58, 92, 94],
    ab: ["Line Breaker", "Switch of Play"],
    nick: "THE ARCHITECT", va: "humanoid_medium",
    i: { head: "PLAIN", back: "NONE", marking: "PATCH", build: "NORMAL", prop: "BALL", scale: 0.98 },
  },
  // ---- Second ten -------------------------------------------------------
  //
  // Roles the first ten left uncovered: a winger, a holding midfielder, a
  // full-back, a target man, a sweeper-keeper, a poacher, a ball-playing
  // centre back, a second-striker, a set-piece specialist and a veteran.
  // Same six stats, same five axes, no new engine anything.
  {
    n: "The Atlantic Winger", w: null, u: "Original", t: "Hugs the touchline, then disappears inside",
    g: ["winger", "speed", "technical", "flair"],
    s: [74, 78, 95, 60, 90, 70],
    ab: ["Chalk on the Boots", "Whipped Cross"],
    nick: "THE WINGER", va: "humanoid_medium",
    i: { head: "PLAIN", back: "NONE", marking: "SPOTS", build: "SLIGHT", prop: "BALL", scale: 0.92 },
  },
  {
    n: "The Anchor", w: null, u: "Original", t: "Nothing comes through the middle",
    g: ["defensive", "tactical", "physical", "midfielder"],
    s: [44, 86, 58, 90, 70, 92],
    ab: ["Screen the Back Four", "Break It Up"],
    nick: "THE ANCHOR", va: "humanoid_medium",
    i: { head: "HELM", back: "NONE", marking: "PLAIN", build: "HEAVY", prop: "BALL", scale: 1.00 },
  },
  {
    n: "The Overlapping Fullback", w: null, u: "Original", t: "Somehow always up for the cross",
    g: ["defender", "speed", "physical", "winger"],
    s: [56, 78, 92, 82, 76, 80],
    ab: ["Overlap", "Recovery Sprint"],
    nick: "THE OVERLAP", va: "humanoid_medium",
    i: { head: "PLAIN", back: "NONE", marking: "BANDS", build: "NORMAL", prop: "BALL", scale: 0.98 },
  },
  {
    n: "The Target Man", w: null, u: "Original", t: "Everything goes through him first",
    g: ["striker", "physical", "aerial", "target"],
    s: [88, 66, 54, 96, 66, 82],
    ab: ["Hold It Up", "Flick On"],
    nick: "THE TARGET", va: "humanoid_large",
    i: { head: "PLAIN", back: "NONE", marking: "PLAIN", build: "HEAVY", prop: "BALL", scale: 1.06 },
  },
  {
    n: "The Sweeper Keeper", w: null, u: "Original", t: "Plays as an eleventh outfielder",
    g: ["keeper", "defensive", "technical", "tactical"],
    s: [24, 90, 66, 82, 84, 94],
    ab: ["Off the Line", "Start the Attack"],
    nick: "THE SWEEPER", va: "humanoid_large",
    i: { head: "HELM", back: "NONE", marking: "STRIPES", build: "TOWERING", prop: "SHIELD", scale: 1.00 },
  },
  {
    n: "The Six Yard Poacher", w: null, u: "Original", t: "Never touches the ball until it matters",
    g: ["striker", "finisher"],
    s: [97, 58, 76, 62, 74, 88],
    ab: ["Right Place", "One Touch"],
    nick: "THE POACHER", va: "humanoid_medium",
    i: { head: "PLAIN", back: "NONE", marking: "PATCH", build: "SQUAT", prop: "BALL", scale: 0.94 },
  },
  {
    n: "The Ball Playing Centre Back", w: null, u: "Original", t: "Defends by having the ball",
    g: ["defender", "defensive", "technical", "tactical"],
    s: [46, 90, 62, 88, 86, 90],
    ab: ["Step Into Midfield", "Diagonal"],
    nick: "THE LIBERO", va: "humanoid_large",
    i: { head: "PLAIN", back: "NONE", marking: "BANDS", build: "HEAVY", prop: "BALL", scale: 1.04 },
  },
  {
    n: "The Second Striker", w: null, u: "Original", t: "Lives in the space nobody marks",
    g: ["striker", "playmaker", "technical", "flair"],
    s: [86, 88, 80, 58, 88, 78],
    ab: ["Between the Lines", "Give and Go"],
    nick: "THE SHADOW", va: "humanoid_medium",
    i: { head: "PLAIN", back: "MANE", marking: "SPOTS", build: "SLIGHT", prop: "BALL", scale: 0.94 },
  },
  {
    n: "The Set Piece Specialist", w: null, u: "Original", t: "The wall never helps",
    g: ["technical", "midfielder", "tactical"],
    s: [82, 84, 56, 64, 96, 90],
    ab: ["Over the Wall", "Inswinger"],
    nick: "THE DEAD BALL", va: "humanoid_medium",
    i: { head: "PLAIN", back: "NONE", marking: "STRIPES", build: "NORMAL", prop: "BALL", scale: 1.02 },
  },
  {
    n: "The Veteran Captain", w: null, u: "Original", t: "Slower every year, later to be beaten",
    g: ["defender", "tactical", "defensive", "physical"],
    s: [52, 94, 48, 84, 74, 98],
    ab: ["Read the Room", "Last Ditch"],
    nick: "THE CAPTAIN", va: "humanoid_large",
    i: { head: "HELM", back: "MANE", marking: "PLAIN", build: "NORMAL", prop: "SHIELD", scale: 1.02 },
  },
  // ---- Missing tactical roles ------------------------------------------------
  {
    n: "The Trequartista", w: null, u: "Original", t: "Finds the pocket of space nobody else sees",
    g: ["playmaker", "technical", "flair", "midfielder"],
    s: [82, 94, 76, 48, 96, 86],
    ab: ["Pocket of Space", "Flip It"],
    nick: "THE TREQUARTISTA", va: "humanoid_medium",
    i: { head: "PLAIN", back: "NONE", marking: "PATCH", build: "SLIGHT", prop: "BALL", scale: 0.92 },
  },
  {
    n: "The False Nine", w: null, u: "Original", t: "Drops deep and unlocks the whole defence",
    g: ["playmaker", "striker", "technical", "tactical"],
    s: [78, 96, 80, 52, 90, 88],
    ab: ["Drag Them Out", "Runner From Deep"],
    nick: "THE FALSE NINE", va: "humanoid_medium",
    i: { head: "PLAIN", back: "NONE", marking: "SPOTS", build: "NORMAL", prop: "BALL", scale: 1.04 },
  },
  {
    n: "The Inverted Winger", w: null, u: "Original", t: "Hugs the touchline then cuts straight for goal",
    g: ["winger", "striker", "speed", "technical"],
    s: [88, 80, 96, 64, 90, 78],
    ab: ["Inside Cut", "Weak Foot Bullet"],
    nick: "THE INVERTER", va: "humanoid_medium",
    i: { head: "PLAIN", back: "NONE", marking: "STRIPES", build: "SLIGHT", prop: "BALL", scale: 1.00 },
  },
  {
    n: "The Deep-Lying Playmaker", w: null, u: "Original", t: "Starts every attack from twenty yards behind it",
    g: ["playmaker", "tactical", "technical", "midfielder"],
    s: [54, 98, 56, 62, 88, 96],
    ab: ["Long Diagonal", "Turn the Tide"],
    nick: "THE PIVOT", va: "humanoid_medium",
    i: { head: "PLAIN", back: "NONE", marking: "BANDS", build: "NORMAL", prop: "BALL", scale: 1.02 },
  },
  {
    n: "The Box-to-Box Midfielder", w: null, u: "Original", t: "Everywhere at once and never spent",
    g: ["midfielder", "physical", "tactical", "technical"],
    s: [74, 84, 84, 82, 78, 82],
    ab: ["Box Run", "Track Back"],
    nick: "THE BOX-TO-BOX", va: "humanoid_medium",
    i: { head: "PLAIN", back: "NONE", marking: "PLAIN", build: "NORMAL", prop: "BALL", scale: 1.04 },
  },
  {
    n: "The Attacking Right Back", w: null, u: "Original", t: "The third man nobody expects on the overlap",
    g: ["defender", "winger", "speed", "physical"],
    s: [70, 78, 94, 80, 76, 80],
    ab: ["Overlap", "Low Cross"],
    nick: "THE OVERLAP R", va: "humanoid_medium",
    i: { head: "PLAIN", back: "NONE", marking: "BANDS", build: "NORMAL", prop: "BALL", scale: 1.06 },
  },
  {
    n: "The Attacking Left Back", w: null, u: "Original", t: "Left foot like a wand, legs like springs",
    g: ["defender", "winger", "speed", "technical"],
    s: [68, 78, 94, 80, 80, 78],
    ab: ["Whip From Deep", "Overlap Left"],
    nick: "THE OVERLAP L", va: "humanoid_medium",
    i: { head: "PLAIN", back: "NONE", marking: "SPOTS", build: "SLIGHT", prop: "BALL", scale: 0.96 },
  },
  {
    n: "The Classic Sweeper", w: null, u: "Original", t: "Last line before the keeper, reads everything",
    g: ["defender", "defensive", "tactical"],
    s: [36, 84, 64, 90, 68, 96],
    ab: ["Sweeping Run", "Distribution Start"],
    nick: "THE OLD SWEEPER", va: "humanoid_large",
    i: { head: "HELM", back: "NONE", marking: "PLAIN", build: "HEAVY", prop: "SHIELD", scale: 1.00 },
  },
  {
    n: "The Complete Forward", w: null, u: "Original", t: "Goals, hold-up, link-up, aerial — does it all",
    g: ["striker", "physical", "technical", "aerial", "finisher"],
    s: [90, 80, 80, 88, 82, 84],
    ab: ["Chest It Down", "Far Post Attack"],
    nick: "THE COMPLETE", va: "humanoid_large",
    i: { head: "PLAIN", back: "NONE", marking: "STRIPES", build: "HEAVY", prop: "BALL", scale: 1.04 },
  },
  {
    n: "The Regista", w: null, u: "Original", t: "Dictates the tempo from the first minute to the last",
    g: ["playmaker", "tactical", "technical", "midfielder"],
    s: [52, 99, 58, 58, 90, 97],
    ab: ["Metronome Pass", "Switch Field"],
    nick: "THE REGISTA", va: "humanoid_medium",
    i: { head: "PLAIN", back: "NONE", marking: "PATCH", build: "SQUAT", prop: "BALL", scale: 0.90 },
  },
  // ---- Continental and style archetypes ----------------------------------------
  {
    n: "The West African Speedster", w: null, u: "Original", t: "Grass barely touched, already at the byline",
    g: ["winger", "speed", "striker", "flair"],
    s: [86, 70, 99, 74, 80, 68],
    ab: ["First Gear", "Beat the Offside"],
    nick: "THE SPEEDSTER", va: "humanoid_medium",
    i: { head: "PLAIN", back: "NONE", marking: "SPOTS", build: "SLIGHT", prop: "BALL", scale: 1.00 },
  },
  {
    n: "The North African Tactician", w: null, u: "Original", t: "Reads the game three moves before it arrives",
    g: ["midfielder", "tactical", "technical"],
    s: [72, 90, 66, 70, 84, 92],
    ab: ["Press Trigger", "Tempo Change"],
    nick: "THE TACTICIAN", va: "humanoid_medium",
    i: { head: "PLAIN", back: "NONE", marking: "BANDS", build: "NORMAL", prop: "BALL", scale: 0.96 },
  },
  {
    n: "The Eastern European Powerhouse", w: null, u: "Original", t: "Built to last ninety minutes and a replay",
    g: ["physical", "striker", "aerial", "midfielder"],
    s: [76, 72, 68, 96, 70, 84],
    ab: ["Iron Shoulder", "Power Header"],
    nick: "THE POWERHOUSE", va: "humanoid_large",
    i: { head: "PLAIN", back: "NONE", marking: "PLAIN", build: "TOWERING", prop: "BALL", scale: 1.06 },
  },
  {
    n: "The Japanese Technician", w: null, u: "Original", t: "Precision in every touch, every pass, every move",
    g: ["technical", "playmaker", "midfielder"],
    s: [74, 88, 78, 60, 96, 90],
    ab: ["Sharp Turn", "No-Look Feed"],
    nick: "THE TECHNICIAN", va: "humanoid_medium",
    i: { head: "PLAIN", back: "NONE", marking: "PATCH", build: "SLIGHT", prop: "BALL", scale: 0.96 },
  },
  {
    n: "The Korean Industrialist", w: null, u: "Original", t: "Covers every blade of grass, twice",
    g: ["midfielder", "physical", "tactical", "speed"],
    s: [72, 82, 86, 84, 76, 86],
    ab: ["Pressure On", "Ground Covered"],
    nick: "THE INDUSTRIALIST", va: "humanoid_medium",
    i: { head: "PLAIN", back: "NONE", marking: "STRIPES", build: "NORMAL", prop: "BALL", scale: 1.04 },
  },
  {
    n: "The Iranian Stopper", w: null, u: "Original", t: "A fortress planted in the middle of the pitch",
    g: ["defensive", "physical", "tactical", "midfielder"],
    s: [44, 78, 58, 96, 68, 92],
    ab: ["Block The Lane", "Intercept"],
    nick: "THE STOPPER", va: "humanoid_large",
    i: { head: "HELM", back: "NONE", marking: "BANDS", build: "HEAVY", prop: "SHIELD", scale: 1.00 },
  },
  {
    n: "The Mexican Maestro", w: null, u: "Original", t: "Silky touches, vision that bends around defenders",
    g: ["playmaker", "technical", "flair", "midfielder"],
    s: [76, 90, 72, 54, 94, 88],
    ab: ["Spin Move", "Nutmeg Chance"],
    nick: "THE MAESTRO MX", va: "humanoid_medium",
    i: { head: "PLAIN", back: "NONE", marking: "STRIPES", build: "SLIGHT", prop: "BALL", scale: 0.96 },
  },
  {
    n: "The Colombian Dribbler", w: null, u: "Original", t: "Leaves defenders rooted to the spot",
    g: ["flair", "technical", "winger", "speed"],
    s: [82, 86, 90, 56, 96, 74],
    ab: ["Roulette", "Change of Pace"],
    nick: "THE DRIBBLER", va: "humanoid_medium",
    i: { head: "PLAIN", back: "NONE", marking: "BANDS", build: "SLIGHT", prop: "BALL", scale: 0.94 },
  },
  {
    n: "The Uruguayan Fighter", w: null, u: "Original", t: "Never beaten, never finished, never lying down",
    g: ["physical", "defender", "tactical", "midfielder"],
    s: [74, 72, 66, 92, 70, 90],
    ab: ["Hard Tackle", "Win It Back"],
    nick: "THE FIGHTER", va: "humanoid_large",
    i: { head: "HELM", back: "NONE", marking: "STRIPES", build: "HEAVY", prop: "SHIELD", scale: 1.04 },
  },
  {
    n: "The Dutch Total Player", w: null, u: "Original", t: "Any position, any moment, always right",
    g: ["tactical", "technical", "physical", "midfielder"],
    s: [80, 90, 84, 76, 86, 86],
    ab: ["Position Swap", "Team Press"],
    nick: "THE TOTALIST", va: "humanoid_medium",
    i: { head: "PLAIN", back: "NONE", marking: "STRIPES", build: "NORMAL", prop: "BALL", scale: 1.06 },
  },
  {
    n: "The Belgian Number Ten", w: null, u: "Original", t: "Goals and assists from the position everyone watches",
    g: ["playmaker", "striker", "technical", "flair"],
    s: [86, 88, 76, 68, 92, 82],
    ab: ["Through Ball", "Shot Off Turn"],
    nick: "THE TEN", va: "humanoid_medium",
    i: { head: "PLAIN", back: "NONE", marking: "PATCH", build: "NORMAL", prop: "BALL", scale: 1.00 },
  },
  {
    n: "The Croatian Mechanic", w: null, u: "Original", t: "Grinds the game, makes it look effortless",
    g: ["midfielder", "tactical", "technical", "physical"],
    s: [68, 88, 72, 76, 84, 92],
    ab: ["Recycled Ball", "Midfield Shield"],
    nick: "THE MECHANIC", va: "humanoid_medium",
    i: { head: "PLAIN", back: "NONE", marking: "BANDS", build: "NORMAL", prop: "BALL", scale: 1.04 },
  },
  {
    n: "The Greek Stopper", w: null, u: "Original", t: "Blocks, heads, wins — the art of the simple",
    g: ["defender", "physical", "defensive", "aerial"],
    s: [38, 72, 56, 98, 62, 90],
    ab: ["Header Clearance", "Physical Presence"],
    nick: "THE GREEK WALL", va: "humanoid_large",
    i: { head: "HELM", back: "NONE", marking: "PLAIN", build: "TOWERING", prop: "SHIELD", scale: 1.08 },
  },
  {
    n: "The Australian Battler", w: null, u: "Original", t: "Runs harder in the second half than the first",
    g: ["physical", "midfielder", "tactical"],
    s: [72, 76, 82, 86, 70, 86],
    ab: ["Second Wind", "Never Say Die"],
    nick: "THE BATTLER", va: "humanoid_medium",
    i: { head: "PLAIN", back: "NONE", marking: "SPOTS", build: "NORMAL", prop: "BALL", scale: 1.00 },
  },
  {
    n: "The Senegalese Powerhouse", w: null, u: "Original", t: "Explosive, imposing, impossible to stop",
    g: ["physical", "striker", "aerial", "speed"],
    s: [84, 68, 88, 96, 72, 76],
    ab: ["Physical Bulldoze", "Hold and Spin"],
    nick: "THE FORCE", va: "humanoid_large",
    i: { head: "PLAIN", back: "NONE", marking: "STRIPES", build: "TOWERING", prop: "BALL", scale: 1.08 },
  },
  // ---- Women's football archetypes ---------------------------------------------
  {
    n: "The American Powerhouse", w: null, u: "Original", t: "Stronger, faster, more determined than anyone on the pitch",
    g: ["striker", "physical", "speed", "finisher"],
    s: [84, 74, 84, 82, 72, 82],
    ab: ["Full Force Run", "Athletic Finish"],
    nick: "THE AMERICAN", va: "humanoid_medium",
    i: { head: "PLAIN", back: "MANE", marking: "STRIPES", build: "NORMAL", prop: "BALL", scale: 0.98 },
  },
  {
    n: "The Swedish Defender", w: null, u: "Original", t: "Nothing passes through, nothing goes above",
    g: ["defender", "physical", "tactical", "aerial"],
    s: [42, 82, 60, 90, 76, 94],
    ab: ["Aerial Command", "Positional Lock"],
    nick: "THE NORDIC WALL", va: "humanoid_large",
    i: { head: "HELM", back: "MANE", marking: "BANDS", build: "HEAVY", prop: "SHIELD", scale: 1.04 },
  },
  {
    n: "The Norwegian Goal Machine", w: null, u: "Original", t: "Clinical, powerful, unstoppable in the box",
    g: ["striker", "physical", "finisher", "aerial"],
    s: [94, 68, 82, 84, 74, 82],
    ab: ["Power Drive", "Penalty Box Predator"],
    nick: "THE GOAL MACHINE", va: "humanoid_medium",
    i: { head: "PLAIN", back: "MANE", marking: "PLAIN", build: "NORMAL", prop: "BALL", scale: 1.00 },
  },
  {
    n: "The Brazilian Flair Artist", w: null, u: "Original", t: "Where skill meets spectacle",
    g: ["flair", "technical", "winger", "playmaker"],
    s: [78, 88, 86, 56, 96, 72],
    ab: ["Samba Step", "Draw the Crowd"],
    nick: "THE ARTIST", va: "humanoid_medium",
    i: { head: "PLAIN", back: "NONE", marking: "SPOTS", build: "SLIGHT", prop: "BALL", scale: 0.94 },
  },
  {
    n: "The English Lioness", w: null, u: "Original", t: "Leads from the front, fights until the whistle",
    g: ["defender", "physical", "tactical", "leader"],
    s: [70, 80, 72, 88, 72, 94],
    ab: ["Armband Authority", "Last Line Stand"],
    nick: "THE LIONESS", va: "humanoid_medium",
    i: { head: "HELM", back: "MANE", marking: "BANDS", build: "NORMAL", prop: "SHIELD", scale: 1.00 },
  },
  {
    n: "The Spanish Schemer", w: null, u: "Original", t: "Ball control and vision that makes time stand still",
    g: ["playmaker", "technical", "tactical", "midfielder"],
    s: [68, 94, 70, 52, 94, 92],
    ab: ["Tiki Touch", "Open the Gate"],
    nick: "THE SCHEMER", va: "humanoid_medium",
    i: { head: "PLAIN", back: "NONE", marking: "PATCH", build: "SLIGHT", prop: "BALL", scale: 0.90 },
  },
  {
    n: "The Canadian Shot Stopper", w: null, u: "Original", t: "Elastic, fearless, fills the goal",
    g: ["keeper", "defensive", "technical", "tactical"],
    s: [18, 82, 62, 90, 80, 96],
    ab: ["Spread the Body", "Penalty Read"],
    nick: "THE SHOT STOPPER", va: "humanoid_large",
    i: { head: "HELM", back: "NONE", marking: "STRIPES", build: "HEAVY", prop: "SHIELD", scale: 1.00 },
  },
  {
    n: "The Pressing Forward", w: null, u: "Original", t: "First line of defence, last line of attack",
    g: ["striker", "speed", "physical", "tactical"],
    s: [80, 78, 94, 72, 76, 80],
    ab: ["High Press", "Counter Steal"],
    nick: "THE PRESSER", va: "humanoid_medium",
    i: { head: "PLAIN", back: "NONE", marking: "SPOTS", build: "NORMAL", prop: "BALL", scale: 0.98 },
  },
  // ---- Historical archetypes ---------------------------------------------------
  {
    n: "The Classic Libero", w: null, u: "Original", t: "Sweeps, reads, builds — the original free defender",
    g: ["defender", "defensive", "tactical", "playmaker"],
    s: [44, 88, 66, 86, 72, 96],
    ab: ["Sweeping Read", "Launch the Attack"],
    nick: "THE CLASSIC LIBERO", va: "humanoid_large",
    i: { head: "PLAIN", back: "NONE", marking: "PLAIN", build: "NORMAL", prop: "BALL", scale: 1.02 },
  },
  {
    n: "The Catenaccio Stopper", w: null, u: "Original", t: "The door is closed. It has always been closed.",
    g: ["defender", "physical", "defensive"],
    s: [32, 76, 52, 99, 58, 92],
    ab: ["Lock the Zone", "Zonal Deny"],
    nick: "THE CATENACCIO", va: "humanoid_large",
    i: { head: "HELM", back: "NONE", marking: "PLAIN", build: "HEAVY", prop: "SHIELD", scale: 1.06 },
  },
  {
    n: "The Long Ball Specialist", w: null, u: "Original", t: "Over the top, before you've had a chance to think",
    g: ["striker", "physical", "aerial", "target"],
    s: [78, 62, 66, 94, 60, 80],
    ab: ["Hoof It", "Aerial Contest"],
    nick: "THE LONG BALL", va: "humanoid_large",
    i: { head: "PLAIN", back: "NONE", marking: "BANDS", build: "TOWERING", prop: "BALL", scale: 1.06 },
  },
  {
    n: "The Inside Forward", w: null, u: "Original", t: "The classic wide attacker who drifts inward and finishes",
    g: ["winger", "striker", "technical", "flair"],
    s: [86, 84, 88, 60, 88, 76],
    ab: ["Drift Inside", "Instep Shot"],
    nick: "THE INSIDE FORWARD", va: "humanoid_medium",
    i: { head: "PLAIN", back: "NONE", marking: "STRIPES", build: "NORMAL", prop: "BALL", scale: 0.96 },
  },
  {
    n: "The Centre Half", w: null, u: "Original", t: "Wins the header, clears the danger, asks no questions",
    g: ["defender", "physical", "defensive", "aerial"],
    s: [44, 74, 56, 98, 62, 88],
    ab: ["Win the Header", "Boot It Clear"],
    nick: "THE CENTRE HALF", va: "humanoid_large",
    i: { head: "PLAIN", back: "NONE", marking: "PLAIN", build: "TOWERING", prop: "SHIELD", scale: 1.06 },
  },
  {
    n: "The Pressing Pioneer", w: null, u: "Original", t: "Invented the idea that you could win the ball this high",
    g: ["midfielder", "tactical", "physical", "speed"],
    s: [72, 86, 90, 82, 76, 82],
    ab: ["Gegenbewegung", "Press Initiate"],
    nick: "THE PIONEER", va: "humanoid_medium",
    i: { head: "PLAIN", back: "NONE", marking: "BANDS", build: "NORMAL", prop: "BALL", scale: 1.00 },
  },
  {
    n: "The Traditional Winger", w: null, u: "Original", t: "Touchline, cross, repeat — a lost art",
    g: ["winger", "speed", "technical"],
    s: [70, 74, 97, 58, 82, 70],
    ab: ["Chalk on Boots", "Early Cross"],
    nick: "THE TOUCHLINE", va: "humanoid_medium",
    i: { head: "PLAIN", back: "NONE", marking: "SPOTS", build: "SLIGHT", prop: "BALL", scale: 0.88 },
  },
];