import type { PoolEntry } from "../types";

/**
 * HOLLYWOOD — stats in order: strength, speed, combat, weapons, tactics, stamina.
 *
 * IP-free archetypes. Original character IDs are unchanged in the database;
 * only names, titles, abilities and universe labels have been replaced.
 * All entries carry w:null so the wiki-enrich script never overwrites them.
 * Game ratings are invented for DRAFT WAR, not an official ranking.
 *
 * Name rule: the archetype describes a general role or style, not the actor's
 * real-world signature trait, catchphrase, or a specific scene/film title.
 */
export const HOLLYWOOD: PoolEntry[] = [
  { n: "The Stunt Perfectionist",   w: null, u: "Hollywood", t: "He does it himself because nobody else will do it right.",                          g: ["veteran","gunplay","mobility","tactical"],         s: [70,88,78,84,88,92], ab: ["Stunt Run","Halo Jump"],                  va: "humanoid_medium", i: { head:"PLAIN", back:"SHELL", marking:"PLAIN",   build:"NORMAL",   prop:"NONE",  scale:1.00 } },
  { n: "The Reliable Brawler",      w: null, u: "Hollywood", t: "He turns up, trains hard, and leaves the villain on the floor.",                   g: ["martial-arts","gunplay","melee"],                  s: [78,84,90,86,82,86], ab: ["Close Quarters","Improvised Weapon"],     va: "humanoid_medium", i: { head:"PLAIN", back:"NONE",  marking:"PLAIN",   build:"SLIGHT",   prop:"NONE",  scale:0.96 } },
  { n: "The Crowd Powerhouse",      w: null, u: "Hollywood", t: "The crowd shows up because they know the problem gets solved.",                    g: ["muscle","wrestler","brawler"],                    s: [94,70,78,72,76,84], ab: ["Power Slam","Crowd Presence"],            va: "humanoid_large",  i: { head:"PLAIN", back:"NONE",  marking:"PLAIN",   build:"HEAVY",    prop:"NONE",  scale:1.10 } },
  { n: "The Blockbuster Heavyweight",w: null, u: "Hollywood", t: "Leads with presence. Lands with conviction.",                                    g: ["muscle","melee"],                                 s: [86,72,74,72,72,80], ab: ["Hammer Swing","Big Screen Charge"],        va: "humanoid_large",  i: { head:"PLAIN", back:"NONE",  marking:"PLAIN",   build:"TOWERING", prop:"NONE",  scale:1.14 } },
  { n: "The Disciplined Combatant", w: null, u: "Hollywood", t: "He never stops the drill. He just finds a new target.",                           g: ["muscle","gunplay","melee"],                       s: [86,74,80,86,78,80], ab: ["Combat Lock","Sword Form"],                va: "humanoid_large",  i: { head:"PLAIN", back:"NONE",  marking:"PLAIN",   build:"HEAVY",    prop:"BLADE", scale:1.06 } },
  { n: "The Precision Operative",   w: null, u: "Hollywood", t: "He mapped the room before anyone touched the door.",                              g: ["gunplay","martial-arts","marksman"],               s: [70,82,88,94,84,84], ab: ["Tactical Reload","Weapon Kata"],           va: "humanoid_medium", i: { head:"PLAIN", back:"NONE",  marking:"PLAIN",   build:"NORMAL",   prop:"NONE",  scale:1.00 } },
  { n: "The Close-Combat Veteran",  w: null, u: "Hollywood", t: "He does not waste a movement because he trained not to.",                         g: ["martial-arts","melee","veteran"],                  s: [74,90,95,70,82,86], ab: ["Rapid Strike","Blade Form"],               va: "humanoid_medium", i: { head:"PLAIN", back:"NONE",  marking:"PLAIN",   build:"SLIGHT",   prop:"BLADE", scale:0.95 } },
  { n: "The Forms Master",          w: null, u: "Hollywood", t: "Speed is the argument and he has never lost it.",                                 g: ["martial-arts","melee","veteran","mobility"],       s: [66,90,92,64,78,80], ab: ["Forms Flow","Weapon Forms"],               va: "humanoid_medium", i: { head:"PLAIN", back:"MANE",  marking:"PLAIN",   build:"SLIGHT",   prop:"NONE",  scale:0.93 } },
  { n: "The Improvised Brawler",    w: null, u: "Hollywood", t: "He has never needed a weapon when there was a chair nearby.",                     g: ["martial-arts","veteran","mobility","environment"], s: [70,86,90,62,86,88], ab: ["Prop Fighting","Acrobatic Escape"],         va: "humanoid_medium", i: { head:"PLAIN", back:"NONE",  marking:"PLAIN",   build:"SQUAT",    prop:"NONE",  scale:0.92 } },
  { n: "The Martial Arts Machine",  w: null, u: "Hollywood", t: "He trains until the choreography becomes instinct.",                              g: ["martial-arts","melee","mobility"],                 s: [80,90,93,70,74,88], ab: ["Spinning Kick","Fight Choreography"],      va: "humanoid_medium", i: { head:"PLAIN", back:"CAPE",  marking:"PLAIN",   build:"NORMAL",   prop:"NONE",  scale:0.98 } },
  { n: "The Athletic Kickboxer",    w: null, u: "Hollywood", t: "He finds the angle no one else takes and punishes it.",                           g: ["martial-arts","veteran","melee"],                  s: [76,82,86,62,68,76], ab: ["Aerial Kick","Kickboxing"],                va: "humanoid_medium", i: { head:"PLAIN", back:"MANE",  marking:"PLAIN",   build:"NORMAL",   prop:"NONE",  scale:0.94 } },
  { n: "The Blade-Sharp Veteran",   w: null, u: "Hollywood", t: "He moves through the fight like he already saw it.",                             g: ["martial-arts","melee","gunplay"],                  s: [74,84,86,80,76,80], ab: ["Blade Work","Vertical Takedown"],           va: "humanoid_medium", i: { head:"PLAIN", back:"CAPE",  marking:"PLAIN",   build:"SLIGHT",   prop:"BLADE", scale:0.94 } },
  { n: "The Original Heavyweight",  w: null, u: "Hollywood", t: "He defined the template everyone else has been following.",                       g: ["muscle","veteran","gunplay","ranged"],             s: [95,58,74,90,78,82], ab: ["Minigun","One Liner"],                     va: "humanoid_large",  i: { head:"PLAIN", back:"SHELL", marking:"PLAIN",   build:"TOWERING", prop:"NONE",  scale:1.18 } },
  { n: "The One Who Keeps Going",   w: null, u: "Hollywood", t: "He has been counted out enough times to stop counting.",                          g: ["muscle","veteran","survival","gunplay"],           s: [90,60,80,86,76,92], ab: ["Last Round","Survival Instinct"],           va: "humanoid_large",  i: { head:"PLAIN", back:"SPINES",marking:"PLAIN",   build:"HEAVY",    prop:"NONE",  scale:1.08 } },
  { n: "The Urban Escapist",        w: null, u: "Hollywood", t: "He finds a way out because giving up was never part of the plan.",                g: ["veteran","gunplay","survival","tactical"],         s: [72,58,68,84,86,82], ab: ["Emergency Escape","Improvised Plan"],       va: "humanoid_medium", i: { head:"PLAIN", back:"SPINES",marking:"PLAIN",   build:"NORMAL",   prop:"NONE",  scale:1.01 } },
  { n: "The Patient Hunter",        w: null, u: "Hollywood", t: "He finds anyone. He has never needed to explain how.",                            g: ["veteran","gunplay","tactical"],                   s: [70,56,74,82,90,72], ab: ["Interrogation","Methodical Pursuit"],       va: "humanoid_medium", i: { head:"PLAIN", back:"FIN",   marking:"PLAIN",   build:"NORMAL",   prop:"NONE",  scale:1.02 } },
  { n: "The Ring Crossover",        w: null, u: "Hollywood", t: "He came from the ring and brought everything with him.",                          g: ["wrestler","muscle","brawler"],                    s: [92,66,78,70,70,86], ab: ["Attitude Adjustment","Never Give Up"],      va: "humanoid_large",  i: { head:"PLAIN", back:"FIN",   marking:"PLAIN",   build:"HEAVY",    prop:"NONE",  scale:1.06 } },
  { n: "The Heavy With Timing",     w: null, u: "Hollywood", t: "He hits hard and hits last. The pause before is part of it.",                     g: ["wrestler","muscle","brawler"],                    s: [93,64,80,70,74,82], ab: ["Bomb Drop","Deadpan Counter"],              va: "humanoid_large",  i: { head:"PLAIN", back:"SPINES",marking:"STRIPES",  build:"TOWERING", prop:"NONE",  scale:1.12 } },
  { n: "The Fighting Shape Lead",   w: null, u: "Hollywood", t: "He trains for the role until it is real.",                                        g: ["muscle","melee","brawler"],                       s: [80,78,82,60,74,84], ab: ["Boxing Combination","Southpaw"],            va: "humanoid_medium", i: { head:"PLAIN", back:"NONE",  marking:"PLAIN",   build:"NORMAL",   prop:"BLADE", scale:0.99 } },
  { n: "The Commanding Presence",   w: null, u: "Hollywood", t: "He walks into the room and people rethink their plans.",                          g: ["veteran","gunplay","tactical","leader"],           s: [78,66,70,78,86,76], ab: ["Command Voice","Cold Read"],                va: "humanoid_large",  i: { head:"PLAIN", back:"CAPE",  marking:"PLAIN",   build:"NORMAL",   prop:"NONE",  scale:1.04 } },
  { n: "The Explosive Striker",     w: null, u: "Hollywood", t: "He uses every part of his body as a weapon and opponents run out of defences.",   g: ["martial-arts","melee","mobility"],                 s: [74,90,92,56,68,84], ab: ["Flying Knee","Elbow Strike"],               va: "humanoid_medium", i: { head:"PLAIN", back:"SHELL", marking:"PLAIN",   build:"SLIGHT",   prop:"NONE",  scale:0.92 } },
  { n: "The Chain Fighter",         w: null, u: "Hollywood", t: "He dismantles everything in reach before it can organise.",                       g: ["martial-arts","melee","mobility"],                 s: [74,92,95,66,72,88], ab: ["Fluid Chain","Corridor Fight"],             va: "humanoid_medium", i: { head:"PLAIN", back:"CAPE",  marking:"PLAIN",   build:"SLIGHT",   prop:"NONE",  scale:0.96 } },
  { n: "The Wire Work Veteran",     w: null, u: "Hollywood", t: "She brings gravitas to every move, even the impossible ones.",                    g: ["martial-arts","veteran","melee","tactical"],       s: [60,82,88,66,88,78], ab: ["Wire Form","Blade Dance"],                  va: "humanoid_medium", i: { head:"PLAIN", back:"SHELL", marking:"PLAIN",   build:"SLIGHT",   prop:"BLADE", scale:0.93 } },
  { n: "The Precise Bruiser",       w: null, u: "Hollywood", t: "She hits with intent and does not stop until the scene is done.",                 g: ["martial-arts","melee","gunplay"],                  s: [70,84,88,80,84,84], ab: ["Stairwell Fight","Cable Choke"],            va: "humanoid_medium", i: { head:"PLAIN", back:"SPINES",marking:"PLAIN",   build:"NORMAL",   prop:"BLADE", scale:0.98 } },
  { n: "The Blockbuster Poise",     w: null, u: "Hollywood", t: "She moves through the frame as if she owns all of it.",                           g: ["melee","veteran"],                                s: [66,74,70,68,72,72], ab: ["Shield Guard","Charge"],                    va: "humanoid_medium", i: { head:"PLAIN", back:"NONE",  marking:"PLAIN",   build:"SLIGHT",   prop:"SHIELD",scale:0.95 } },
  { n: "The Blade Movie Lead",      w: null, u: "Hollywood", t: "She learned everything required and then exceeded it.",                           g: ["martial-arts","melee","revenge"],                  s: [60,78,82,74,80,76], ab: ["Katana Form","Roaring Rampage"],            va: "humanoid_medium", i: { head:"PLAIN", back:"MANE",  marking:"PLAIN",   build:"SLIGHT",   prop:"BLADE", scale:0.97 } },
  { n: "The Franchise Survivor",    w: null, u: "Hollywood", t: "She has run the gauntlet in every instalment and has not slowed down.",           g: ["gunplay","mobility","survival"],                  s: [60,80,78,84,74,80], ab: ["Dual Wield","Clear the Room"],              va: "humanoid_medium", i: { head:"PLAIN", back:"FIN",   marking:"PLAIN",   build:"SLIGHT",   prop:"NONE",  scale:0.92 } },
  { n: "The Original Final Girl",   w: null, u: "Hollywood", t: "She defined the archetype and never stopped being it.",                           g: ["veteran","survival","tactical","ranged"],          s: [62,56,60,80,90,74], ab: ["Loader Suit","Hold the Line"],              va: "humanoid_medium", i: { head:"PLAIN", back:"SHELL", marking:"PLAIN",   build:"SQUAT",    prop:"NONE",  scale:0.99 } },
  { n: "The Crew Enforcer",         w: null, u: "Hollywood", t: "He will make sure nothing separates the crew from the finish line.",              g: ["muscle","brawler","leader"],                      s: [90,66,74,72,72,80], ab: ["Ram Charge","Crew Call"],                   va: "humanoid_large",  i: { head:"PLAIN", back:"CAPE",  marking:"PLAIN",   build:"HEAVY",    prop:"NONE",  scale:1.05 } },
  { n: "The Blue-Collar Lead",      w: null, u: "Hollywood", t: "He does not stop for the audience. He stops when it is over.",                    g: ["muscle","gunplay","military"],                    s: [78,70,74,80,74,78], ab: ["Marksman Training","Grit"],                 va: "humanoid_medium", i: { head:"PLAIN", back:"MANE",  marking:"PLAIN",   build:"NORMAL",   prop:"BLADE", scale:1.01 } },
  { n: "The Thinking Operative",    w: null, u: "Hollywood", t: "He survives on improvisation and never runs out of it.",                          g: ["gunplay","tactical","stealth"],                   s: [68,78,82,76,90,82], ab: ["Improvised Counter","Tradecraft"],           va: "humanoid_medium", i: { head:"PLAIN", back:"SHELL", marking:"PLAIN",   build:"NORMAL",   prop:"BLADE", scale:0.97 } },
  { n: "The Blunt Instrument",      w: null, u: "Hollywood", t: "He is not subtle and has never needed to be.",                                    g: ["gunplay","tactical","veteran"],                   s: [80,74,82,88,88,84], ab: ["Parkour Chase","Sidearm"],                  va: "humanoid_medium", i: { head:"PLAIN", back:"SPINES",marking:"PLAIN",   build:"HEAVY",    prop:"NONE",  scale:1.03 } },
  { n: "The Intense One",           w: null, u: "Hollywood", t: "He commits to the role and the room clears.",                                     g: ["muscle","brawler","melee"],                       s: [84,70,80,68,78,82], ab: ["Clinch Work","Mask Menace"],                va: "humanoid_medium", i: { head:"PLAIN", back:"MANE",  marking:"PLAIN",   build:"HEAVY",    prop:"NONE",  scale:1.06 } },
  { n: "The Decade Headliner",      w: null, u: "Hollywood", t: "He has been in character long enough that the character is him.",                 g: ["muscle","melee","veteran"],                       s: [82,72,78,64,74,84], ab: ["Berserker Take","Stage Stamina"],            va: "humanoid_large",  i: { head:"PLAIN", back:"CAPE",  marking:"PLAIN",   build:"HEAVY",    prop:"BLADE", scale:1.08 } },
  { n: "The Squad Leader",          w: null, u: "Hollywood", t: "He leads because someone has to and he happens to be very good at it.",           g: ["muscle","melee","leader"],                        s: [80,74,78,68,78,80], ab: ["Guard Form","Squad Lead"],                  va: "humanoid_medium", i: { head:"PLAIN", back:"NONE",  marking:"PLAIN",   build:"NORMAL",   prop:"SHIELD",scale:1.00 } },
  { n: "The Quip Choreographer",    w: null, u: "Hollywood", t: "He talks during the fight because he is winning it.",                             g: ["gunplay","melee","mobility"],                     s: [66,76,74,76,74,74], ab: ["Motormouth","Dual Katana"],                 va: "humanoid_medium", i: { head:"PLAIN", back:"FIN",   marking:"PLAIN",   build:"NORMAL",   prop:"BLADE", scale:0.98 } },
  { n: "The Tournament Legend",     w: null, u: "Hollywood", t: "He became the legend and the legend turned out to be accurate.",                  g: ["martial-arts","veteran","melee"],                  s: [76,70,86,72,72,76], ab: ["Roundhouse","Tournament Pedigree"],          va: "humanoid_medium", i: { head:"PLAIN", back:"NONE",  marking:"PLAIN",   build:"SQUAT",    prop:"BLADE", scale:0.91 } },
  { n: "The Heavy And Fast",        w: null, u: "Hollywood", t: "He is too large to move that quickly and does it anyway.",                        g: ["martial-arts","veteran","brawler"],                s: [84,78,90,60,80,74], ab: ["Ground Control","Choreography Mind"],        va: "humanoid_large",  i: { head:"PLAIN", back:"NONE",  marking:"PLAIN",   build:"SQUAT",    prop:"NONE",  scale:1.04 } },
  { n: "The Set-Trained Fighter",   w: null, u: "Hollywood", t: "She learned it under camera lights and took it further than the role required.",  g: ["martial-arts","gunplay","stealth"],                s: [56,80,80,78,78,76], ab: ["Wire Kick","Infiltrate"],                   va: "humanoid_medium", i: { head:"PLAIN", back:"SPINES",marking:"PLAIN",   build:"SLIGHT",   prop:"NONE",  scale:0.90 } },
  { n: "The Franchise Fighter",     w: null, u: "Hollywood", t: "She has anchored three franchises and improved on each.",                         g: ["melee","mobility","gunplay"],                     s: [60,78,76,72,74,76], ab: ["Blade Spin","Zero G Move"],                 va: "humanoid_medium", i: { head:"PLAIN", back:"SPINES",marking:"PLAIN",   build:"SLIGHT",   prop:"BLADE", scale:0.91 } },
  { n: "The Unhinged Tactician",    w: null, u: "Hollywood", t: "He plays chaos like an instrument and the enemy never catches up.",               g: ["gunplay","tactical","veteran","chaotic"],          s: [68,66,68,84,92,78], ab: ["Manic Energy","Face Change"],               va: "humanoid_medium", i: { head:"PLAIN", back:"FIN",   marking:"PLAIN",   build:"HEAVY",    prop:"NONE",  scale:0.96 } },
  { n: "The Ballistic Artist",      w: null, u: "Hollywood", t: "He turns the act of shooting into something no one in the room expected to see.", g: ["gunplay","tactical","veteran","marksman"],         s: [68,76,80,96,86,80], ab: ["Gun Ballet","Slow Motion"],                 va: "humanoid_medium", i: { head:"PLAIN", back:"CAPE",  marking:"PLAIN",   build:"NORMAL",   prop:"BLADE", scale:1.00 } },
];
