import type { PoolEntry } from "../types";

/**
 * MARVEL — stats in order: power, speed, durability, combat, intelligence, special.
 *
 * Balance intent: the top end (Thanos, Silver Surfer, Scarlet Witch) sits in the
 * low 90s, the street level (Hawkeye, Punisher) in the high 60s. Nobody leads on
 * every stat — Hulk is a wall with no plan, Professor X is a plan with no body.
 * Game ratings for DRAFT WAR, not an official Marvel ranking.
 */
export const MARVEL: PoolEntry[] = [
  { n: "Spider-Man", u: "Marvel Comics", v: "Comics", t: "Your friendly neighbourhood", g: ["avengers", "street", "mobility"], s: [78, 90, 74, 88, 90, 86], ab: ["Spider-Sense", "Web-Slinging"] },
  { n: "Iron Man", u: "Marvel Cinematic Universe", v: "MCU", t: "Genius, billionaire, philanthropist", g: ["avengers", "tech", "ranged"], s: [88, 80, 86, 76, 96, 90], ab: ["Repulsor Blast", "Suit Up"] },
  { n: "Captain America", u: "Marvel Cinematic Universe", v: "MCU", t: "The first Avenger", g: ["avengers", "leader", "tactical"], s: [70, 68, 74, 96, 84, 74], ab: ["Shield Throw", "Rally"] },
  { n: "Thor", w: "Thor (Marvel Comics)", u: "Marvel Cinematic Universe", v: "MCU", t: "God of Thunder", g: ["avengers", "cosmic", "melee"], s: [96, 88, 94, 88, 70, 94], ab: ["Stormbreaker", "Bifrost Strike"] },
  { n: "Hulk", u: "Marvel Comics", v: "Comics", t: "The angrier, the stronger", g: ["avengers", "brawler", "survival"], s: [98, 62, 98, 72, 56, 88], ab: ["Thunderclap", "Rage"] },
  { n: "Black Panther", w: "Black Panther (character)", u: "Marvel Cinematic Universe", v: "MCU", t: "King of Wakanda", g: ["avengers", "leader", "tech", "melee"], s: [74, 80, 82, 90, 88, 80], ab: ["Kinetic Absorption", "Vibranium Claws"] },
  { n: "Doctor Strange", u: "Marvel Cinematic Universe", v: "MCU", t: "Sorcerer Supreme", g: ["avengers", "cosmic", "tech"], s: [90, 70, 68, 72, 94, 98], ab: ["Mirror Dimension", "Time Loop"] },
  { n: "Scarlet Witch", u: "Marvel Cinematic Universe", v: "MCU", t: "Chaos incarnate", g: ["avengers", "cosmic"], s: [96, 72, 66, 64, 84, 98], ab: ["Chaos Magic", "Reality Warp"] },
  { n: "Wolverine", w: "Wolverine (character)", u: "Marvel Comics", v: "Comics", t: "The best there is", g: ["x-men", "melee", "survival", "brawler"], s: [78, 72, 94, 94, 68, 84], ab: ["Adamantium Claws", "Healing Factor"] },
  { n: "Deadpool", u: "Marvel Comics", v: "Comics", t: "The merc with a mouth", g: ["street", "survival", "ranged"], s: [70, 76, 92, 88, 72, 88], ab: ["Regeneration", "Fourth Wall Break"] },
  { n: "Thanos", u: "Marvel Cinematic Universe", v: "MCU", t: "Inevitable", g: ["villain", "cosmic", "melee"], s: [97, 74, 96, 90, 90, 92], ab: ["Infinity Gauntlet", "Double Strike"] },
  { n: "Loki", w: "Loki (Marvel Comics)", u: "Marvel Cinematic Universe", v: "MCU", t: "God of Mischief", g: ["villain", "stealth", "tactical"], s: [72, 76, 74, 76, 92, 92], ab: ["Illusion Army", "Betrayal"] },
  { n: "Magneto", w: "Magneto (Marvel Comics)", u: "Marvel Comics", v: "Comics", t: "Master of magnetism", g: ["villain", "x-men", "ranged"], s: [94, 66, 74, 70, 92, 94], ab: ["Magnetic Field", "Metal Storm"] },
  { n: "Storm", w: "Storm (Marvel Comics)", u: "Marvel Comics", v: "Comics", t: "Weather goddess", g: ["x-men", "ranged", "leader"], s: [88, 78, 68, 74, 80, 90], ab: ["Lightning Call", "Cyclone"] },
  { n: "Jean Grey", u: "Marvel Comics", v: "Comics", t: "The Phoenix host", g: ["x-men", "cosmic"], s: [95, 72, 66, 64, 86, 97], ab: ["Telekinesis", "Phoenix Force"] },
  { n: "Professor X", u: "Marvel Comics", v: "Comics", t: "The most dangerous mind", g: ["x-men", "leader", "tactical"], s: [84, 38, 46, 48, 98, 94], ab: ["Mind Control", "Astral Projection"] },
  { n: "Captain Marvel", u: "Marvel Cinematic Universe", v: "MCU", t: "Higher, further, faster", g: ["avengers", "cosmic", "mobility"], s: [95, 92, 92, 76, 74, 90], ab: ["Binary Mode", "Photon Blast"] },
  { n: "Vision", u: "Marvel Cinematic Universe", v: "MCU", t: "Mind Stone made flesh", g: ["avengers", "tech"], s: [86, 80, 88, 72, 92, 88], ab: ["Phase Shift", "Mind Beam"] },
  { n: "Ant-Man", u: "Marvel Cinematic Universe", v: "MCU", t: "Size is a weapon", g: ["avengers", "tech", "stealth"], s: [72, 68, 64, 72, 84, 90], ab: ["Giant Form", "Quantum Shrink"] },
  { n: "Wasp", w: "Wasp (character)", u: "Marvel Cinematic Universe", v: "MCU", t: "Sting and vanish", g: ["avengers", "tech", "mobility"], s: [66, 82, 60, 80, 82, 84], ab: ["Blaster Sting", "Flight"] },
  { n: "Hawkeye", u: "Marvel Cinematic Universe", v: "MCU", t: "Never misses", g: ["avengers", "street", "marksman", "ranged"], s: [54, 66, 58, 84, 78, 76], ab: ["Trick Arrow", "Perfect Shot"] },
  { n: "Black Widow", w: "Black Widow (Natasha Romanova)", u: "Marvel Cinematic Universe", v: "MCU", t: "Red in the ledger", g: ["avengers", "street", "stealth", "tactical"], s: [52, 72, 58, 90, 86, 70], ab: ["Widow's Bite", "Takedown"] },
  { n: "Daredevil", u: "Marvel Comics", v: "Comics", t: "The man without fear", g: ["street", "melee", "stealth"], s: [58, 76, 64, 92, 82, 86], ab: ["Radar Sense", "Billy Club"] },
  { n: "Punisher", u: "Marvel Comics", v: "Comics", t: "One batch, two batch", g: ["street", "marksman", "military", "ranged"], s: [60, 62, 70, 88, 80, 72], ab: ["Suppressing Fire", "Ambush"] },
  { n: "Moon Knight", u: "Marvel Comics", v: "Comics", t: "Fist of Khonshu", g: ["street", "melee", "stealth"], s: [66, 72, 74, 88, 74, 84], ab: ["Crescent Darts", "Moonlight Surge"] },
  { n: "Silver Surfer", u: "Marvel Comics", v: "Comics", t: "The herald", g: ["cosmic", "mobility", "ranged"], s: [96, 98, 92, 68, 88, 96], ab: ["Power Cosmic", "Board Charge"] },
  { n: "Galactus", u: "Marvel Comics", v: "Comics", t: "Devourer of worlds", g: ["villain", "cosmic"], s: [100, 74, 98, 58, 94, 98], ab: ["World Hunger", "Cosmic Blast"] },
  { n: "Ghost Rider", u: "Marvel Comics", v: "Comics", t: "The spirit of vengeance", g: ["street", "survival", "melee"], s: [92, 72, 90, 78, 64, 96], ab: ["Penance Stare", "Hellfire Chain"] },
  { n: "Venom", w: "Venom (character)", u: "Marvel Comics", v: "Comics", t: "We are Venom", g: ["villain", "street", "brawler"], s: [84, 78, 88, 84, 66, 88], ab: ["Symbiote Tendrils", "Feed"] },
  { n: "Carnage", u: "Marvel Comics", v: "Comics", t: "Chaos with a smile", g: ["villain", "street", "brawler"], s: [86, 82, 84, 82, 56, 92], ab: ["Blade Storm", "Frenzy"] },
  { n: "Green Goblin", u: "Marvel Comics", v: "Comics", t: "The cackling menace", g: ["villain", "street", "tech"], s: [74, 72, 72, 78, 92, 82], ab: ["Pumpkin Bomb", "Glider Charge"] },
  { n: "Doctor Doom", u: "Marvel Comics", v: "Comics", t: "Doom demands", g: ["villain", "tech", "leader"], s: [88, 66, 86, 78, 98, 96], ab: ["Doom Field", "Arcane Circuit"] },
  { n: "Ultron", u: "Marvel Cinematic Universe", v: "MCU", t: "No strings", g: ["villain", "tech"], s: [90, 76, 90, 74, 96, 88], ab: ["Drone Swarm", "Upload"] },
  { n: "Red Skull", u: "Marvel Comics", v: "Comics", t: "Hydra's head", g: ["villain", "tactical", "military"], s: [54, 58, 58, 82, 92, 66], ab: ["Command", "Cosmic Cube Lore"] },
  { n: "Winter Soldier", u: "Marvel Cinematic Universe", v: "MCU", t: "The ghost story", g: ["avengers", "street", "military", "stealth"], s: [66, 72, 72, 90, 80, 72], ab: ["Bionic Arm", "Silent Kill"] },
  { n: "Falcon", w: "Falcon (comics)", u: "Marvel Cinematic Universe", v: "MCU", t: "On your left", g: ["avengers", "mobility", "tech"], s: [56, 78, 60, 80, 76, 80], ab: ["Redwing", "Dive Attack"] },
  { n: "War Machine", u: "Marvel Cinematic Universe", v: "MCU", t: "Heavy ordnance", g: ["avengers", "tech", "ranged", "military"], s: [84, 76, 86, 76, 84, 84], ab: ["Shoulder Cannon", "Barrage"] },
  { n: "Star-Lord", u: "Marvel Cinematic Universe", v: "MCU", t: "Legendary outlaw", g: ["cosmic", "leader", "ranged"], s: [60, 70, 64, 78, 78, 78], ab: ["Element Gun", "Jet Boots"] },
  { n: "Gamora", u: "Marvel Cinematic Universe", v: "MCU", t: "The deadliest woman", g: ["cosmic", "melee", "assassin"], s: [66, 80, 70, 92, 80, 76], ab: ["Godslayer Blade", "Counter"] },
  { n: "Drax the Destroyer", u: "Marvel Cinematic Universe", v: "MCU", t: "Nothing goes over his head", g: ["cosmic", "brawler", "melee"], s: [82, 62, 86, 80, 54, 70], ab: ["Blade Rush", "Unmovable"] },
  { n: "Rocket Raccoon", u: "Marvel Cinematic Universe", v: "MCU", t: "Ain't no raccoon", g: ["cosmic", "tech", "ranged"], s: [54, 76, 56, 76, 94, 84], ab: ["Big Gun", "Improvised Bomb"] },
  { n: "Groot", u: "Marvel Cinematic Universe", v: "MCU", t: "I am Groot", g: ["cosmic", "survival"], s: [84, 50, 92, 66, 56, 88], ab: ["Regrowth", "Root Cage"] },
  { n: "Nebula", w: "Nebula (character)", u: "Marvel Cinematic Universe", v: "MCU", t: "Rebuilt, piece by piece", g: ["cosmic", "melee", "tech"], s: [72, 76, 82, 86, 78, 74], ab: ["Cyber Arm", "Relentless"] },
  { n: "Cyclops", w: "Cyclops (Marvel Comics)", u: "Marvel Comics", v: "Comics", t: "Field leader", g: ["x-men", "leader", "ranged", "tactical"], s: [82, 66, 64, 82, 86, 86], ab: ["Optic Blast", "Battle Plan"] },
  { n: "Beast", u: "Marvel Comics", v: "Comics", t: "Brains and brawn", g: ["x-men", "brawler"], s: [78, 76, 78, 84, 96, 74], ab: ["Acrobatic Assault", "Field Science"] },
  { n: "Nightcrawler", u: "Marvel Comics", v: "Comics", t: "Bamf", g: ["x-men", "mobility", "stealth"], s: [58, 86, 62, 84, 74, 94], ab: ["Teleport Strike", "Vanish"] },
  { n: "Colossus", u: "Marvel Comics", v: "Comics", t: "Organic steel", g: ["x-men", "brawler", "survival"], s: [88, 54, 96, 76, 62, 78], ab: ["Steel Form", "Fastball Special"] },
  { n: "Rogue", u: "Marvel Comics", v: "Comics", t: "Don't touch", g: ["x-men", "brawler"], s: [88, 78, 88, 80, 72, 92], ab: ["Power Absorption", "Flight"] },
  { n: "Mystique", u: "Marvel Comics", v: "Comics", t: "Anyone, anywhere", g: ["villain", "x-men", "stealth", "assassin"], s: [58, 76, 62, 84, 88, 92], ab: ["Shapeshift", "Infiltrate"] },
  { n: "Namor", u: "Marvel Comics", v: "Comics", t: "The Sub-Mariner", g: ["villain", "leader", "brawler"], s: [90, 82, 88, 82, 74, 84], ab: ["Tidal Surge", "Winged Flight"] },
  { n: "Black Cat", w: "Black Cat (Marvel Comics)", u: "Marvel Comics", v: "Comics", t: "Luck has nothing to do with it", g: ["street", "stealth", "mobility"], s: [52, 84, 56, 84, 74, 92], ab: ["Bad Luck Field", "Grappling Hook"] },
  { n: "Taskmaster", w: "Taskmaster (character)", u: "Marvel Comics", v: "Comics", t: "Copies every move in real time", g: ["villain", "melee", "tactical"], s: [66, 78, 68, 98, 86, 88], ab: ["Photographic Reflexes", "Counter Form"] },
  { n: "Spider-Woman", w: "Spider-Woman (Jessica Drew)", u: "Marvel Comics", v: "Comics", t: "Venom blast, pheromones, and flight", g: ["avengers", "spy", "mobility"], s: [76, 80, 72, 86, 78, 90], ab: ["Venom Blast", "Pheromone Cloud"] },
  { n: "Ms. Marvel", w: "Ms. Marvel (Kamala Khan)", u: "Marvel Comics", v: "Comics", t: "Embiggen — her word, her power", g: ["avengers", "street", "brawler"], s: [78, 74, 80, 76, 76, 86], ab: ["Embiggen Fist", "Morphogenic Slam"] },
  { n: "Blade", w: "Blade (character)", u: "Marvel Comics", v: "Comics", t: "The Daywalker hunts in both worlds", g: ["street", "melee", "hunter"], s: [66, 80, 74, 94, 80, 84], ab: ["Blade Sweep", "Daywalker Edge"] },
  { n: "Luke Cage", w: "Luke Cage", u: "Marvel Comics", v: "Comics", t: "Unbreakable skin, iron will", g: ["street", "brawler", "leader"], s: [90, 58, 96, 88, 60, 68], ab: ["Unbreakable", "Power Man Slam"] },
  { n: "Iron Fist", w: "Iron Fist (Marvel Comics)", u: "Marvel Comics", v: "Comics", t: "The immortal weapon of K'un-Lun", g: ["street", "martial-arts", "melee"], s: [64, 82, 68, 96, 74, 92], ab: ["Iron Fist Strike", "Chi Heal"] },
  { n: "She-Hulk", w: "She-Hulk", u: "Marvel Comics", v: "Comics", t: "Stronger, smarter, and still in court by Monday", g: ["avengers", "brawler", "leader"], s: [90, 70, 90, 84, 88, 76], ab: ["Gamma Strength", "Cross-Examination"] },
  { n: "Nova", w: "Nova (Richard Rider)", u: "Marvel Comics", v: "Comics", t: "The Human Rocket at full burn", g: ["cosmic", "ranged", "mobility"], s: [88, 94, 88, 78, 74, 92], ab: ["Nova Force Blast", "Gravimetric Pulse"] },
  { n: "Elektra", w: "Elektra (character)", u: "Marvel Comics", v: "Comics", t: "The Hand's most feared weapon", g: ["street", "assassin", "martial-arts"], s: [60, 88, 64, 98, 82, 84], ab: ["Sai Strike", "Death Touch"] },
];
