import type { PoolEntry } from "../types";

/**
 * VIDEO GAMES — stats in order: power, speed, durability, combat, skill, special.
 *
 * IP-free archetypes. Original character IDs are unchanged in the database;
 * only names, titles, abilities and universe labels have been replaced.
 * All entries carry w:null so the wiki-enrich script never overwrites them.
 * Game ratings are invented for DRAFT WAR, not an official ranking.
 */
export const VIDEO_GAMES: PoolEntry[] = [
  { n: "The Radiant Everyman",    w: null, u: "Games", t: "He is unremarkable until he needs to save a world, which is often.",                           g: ["mobility","brawler"],                          s: [76,80,84,76,82,90],  ab: ["Power Stomp","Growth Boost"],                                         i: { head:"PLAIN", back:"NONE",  marking:"PLAIN",  build:"SQUAT",    prop:"NONE",   scale:0.88 } },
  { n: "The Chosen Wanderer",     w: null, u: "Games", t: "He is chosen repeatedly, which suggests the world runs out of better options.",                g: ["rpg","melee","tactical"],                      s: [78,78,78,90,90,88],  ab: ["Sacred Blade Slash","Guardian Parry"],                                 i: { head:"PLAIN", back:"NONE",  marking:"PLAIN",  build:"NORMAL",   prop:"SHIELD", scale:0.97 } },
  { n: "The Armored Hunter",      w: null, u: "Games", t: "The suit is the plan. The plan is thorough.",                                                  g: ["shooter","ranged"],                            s: [88,76,88,74,88,90],  ab: ["Charge Blast","Sphere Dive"],                                          i: { head:"HELM",  back:"NONE",  marking:"PLAIN",  build:"HEAVY",    prop:"ORB",    scale:1.00 } },
  { n: "The Iron Spartan",        w: null, u: "Games", t: "He was made to be the last resort and kept ending up the first call.",                         g: ["shooter","military","tactical"],               s: [84,78,92,84,90,82],  ab: ["Energy Shield","Suppression Fire"],         va: "humanoid_large", i: { head:"HELM",  back:"NONE",  marking:"PLAIN",  build:"HEAVY",    prop:"NONE",   scale:1.06 } },
  { n: "The Raging Godslayer",    w: null, u: "Games", t: "He did not stop at the first god and had no reason to stop at any of them.",                   g: ["rpg","brawler","melee"],                       s: [98,76,96,94,62,92],  ab: ["Infernal Chain Slash","Wrath Surge"],       va: "humanoid_large", i: { head:"PLAIN", back:"NONE",  marking:"STRIPES",build:"TOWERING", prop:"BLADE",  scale:1.14 } },
  { n: "The Relentless Explorer", w: null, u: "Games", t: "Every tomb was a trap and she walked out of every one.",                                       g: ["shooter","mobility","survival"],               s: [58,84,66,78,92,78],  ab: ["Dual Fire","Vault and Drop"],                                          i: { head:"PLAIN", back:"NONE",  marking:"PLAIN",  build:"SLIGHT",   prop:"NONE",   scale:0.93 } },
  { n: "The Shadow Operative",    w: null, u: "Games", t: "The mission was impossible and he had already started.",                                       g: ["stealth","shooter","tactical","military"],     s: [62,74,70,88,96,84],  ab: ["Field Concealment","Close Combat Takedown"],                           i: { head:"PLAIN", back:"SHELL", marking:"PLAIN",  build:"NORMAL",   prop:"NONE",   scale:0.97 } },
  { n: "The Blinding Streak",     w: null, u: "Games", t: "He solved every obstacle by arriving before it could form.",                                   g: ["mobility"],                                    s: [70,100,64,64,76,88], ab: ["Rolling Blitz","Barrier Dash"],                                        i: { head:"PLAIN", back:"SPINES",marking:"PLAIN",  build:"SLIGHT",   prop:"NONE",   scale:0.88 } },
  { n: "The Sparking Bolt",       w: null, u: "Games", t: "Small, fast, and conducting a charge the enemy never sees coming.",                            g: ["ranged","mobility"],                           s: [76,88,50,60,74,88],  ab: ["Static Shock","Rapid Dodge"],               va: "quadruped_small", i: { head:"PLAIN", back:"NONE",  marking:"STRIPES",build:"NORMAL",   prop:"NONE",   scale:0.75 } },
  { n: "The Unyielding Slayer",   w: null, u: "Games", t: "He was sent to deal with the problem and kept finding more problems.",                         g: ["shooter","brawler","survival"],                s: [94,82,92,90,84,90],  ab: ["Heavy Scatter Shot","Finishing Strike"],    va: "humanoid_large", i: { head:"HELM",  back:"SHELL", marking:"PLAIN",  build:"HEAVY",    prop:"NONE",   scale:1.06 } },
  { n: "The Wandering Warrior",   w: null, u: "Games", t: "He travels to find a fight worthy of the form he has already mastered.",                       g: ["fighter","martial-arts","melee"],              s: [82,80,82,96,92,86],  ab: ["Energy Wave","Rising Uppercut"],                                       i: { head:"PLAIN", back:"NONE",  marking:"PLAIN",  build:"NORMAL",   prop:"NONE",   scale:1.00 } },
  { n: "The Infernal Revenant",   w: null, u: "Games", t: "Death did not stop him. It just gave him a forwarding address.",                               g: ["fighter","melee"],                             s: [86,84,82,92,82,92],  ab: ["Chain Snare","Underworld Blaze"],                                      i: { head:"PLAIN", back:"NONE",  marking:"PLAIN",  build:"NORMAL",   prop:"BLADE",  scale:0.99 } },
  { n: "The Glacial Templar",     w: null, u: "Games", t: "He freezes the field before the fight begins, which is a form of mercy.",                      g: ["fighter","melee","tactical"],                  s: [84,80,84,92,84,90],  ab: ["Frost Clone","Cryo Burst"],                                            i: { head:"PLAIN", back:"MANE",  marking:"PLAIN",  build:"NORMAL",   prop:"NONE",   scale:0.98 } },
  { n: "The Brooding Swordsman",  w: null, u: "Games", t: "He carries more than the sword and fewer people notice the weight.",                           g: ["rpg","melee","swordsman"],                     s: [86,78,82,90,84,88],  ab: ["Heavy Blade Strike","Limit Surge"],                                    i: { head:"PLAIN", back:"MANE",  marking:"PLAIN",  build:"NORMAL",   prop:"BLADE",  scale:1.00 } },
  { n: "The Exiled Sovereign",    w: null, u: "Games", t: "He was the best of his generation until he found something that made that irrelevant.",        g: ["rpg","villain","melee"],                       s: [94,90,86,96,88,96],  ab: ["World Cleave","Celestial Blade"],           va: "winged",         i: { head:"PLAIN", back:"NONE",  marking:"PLAIN",  build:"NORMAL",   prop:"BLADE",  scale:1.02 } },
  { n: "The Brutal King",         w: null, u: "Games", t: "He has tried to win the same way every time and has not stopped trying.",                      g: ["villain","brawler"],                           s: [92,56,94,74,58,84],  ab: ["Flame Breath","Ground Shatter"],            va: "humanoid_large", i: { head:"HORNS", back:"SPINES",marking:"PLAIN",  build:"TOWERING", prop:"NONE",   scale:1.18 } },
  { n: "The Wild Titan",          w: null, u: "Games", t: "He is not the biggest threat in the jungle by a technical standard — just a practical one.",  g: ["brawler","melee"],                             s: [90,66,86,74,62,78],  ab: ["Overhead Smash","Barrel Launch"],           va: "humanoid_large", i: { head:"PLAIN", back:"NONE",  marking:"PLAIN",  build:"HEAVY",    prop:"HAMMER", scale:1.14 } },
  { n: "The Cloaked Assassin",    w: null, u: "Games", t: "He learned the creed, broke it, and found that what he built was better.",                    g: ["stealth","assassin","mobility","melee"],       s: [66,84,70,90,92,84],  ab: ["Concealed Strike","Freefall Escape"],                                  i: { head:"PLAIN", back:"CAPE",  marking:"PLAIN",  build:"SLIGHT",   prop:"BLADE",  scale:0.97 } },
  { n: "The Fortunate Rover",     w: null, u: "Games", t: "Every trap he escaped was technically a near miss, but he stopped counting.",                  g: ["shooter","mobility","survival"],               s: [60,80,72,80,88,80],  ab: ["Lucky Escape","Cover Burst"],                                          i: { head:"PLAIN", back:"FIN",   marking:"PLAIN",  build:"NORMAL",   prop:"NONE",   scale:0.96 } },
  { n: "The Weathered Outlaw",    w: null, u: "Games", t: "He drew a line in dust and kept it when the world tried to erase it.",                        g: ["shooter","marksman","survival"],               s: [72,72,82,84,92,82],  ab: ["Precision Aim","Rope Catch"],                                          i: { head:"PLAIN", back:"NONE",  marking:"PLAIN",  build:"HEAVY",    prop:"NONE",   scale:0.99 } },
  { n: "The Agile Tracker",       w: null, u: "Games", t: "She mapped the machines before the world knew they needed mapping.",                           g: ["rpg","marksman","tactical"],                   s: [64,82,70,82,94,86],  ab: ["Target Scan","Proximity Snare"],                                       i: { head:"PLAIN", back:"NONE",  marking:"PLAIN",  build:"SLIGHT",   prop:"BOW",    scale:0.95 } },
  { n: "The Raucous Slayer",      w: null, u: "Games", t: "Half demon, fully committed, and enjoying every moment of both.",                              g: ["fighter","melee","brawler"],                   s: [92,88,92,94,86,94],  ab: ["Demonic Surge","Style Switch"],                                        i: { head:"PLAIN", back:"SPINES",marking:"PLAIN",  build:"NORMAL",   prop:"BLADE",  scale:1.00 } },
];
