/**
 * Regenerates `supabase/migrations/0004_seed_v2_characters.sql` from the
 * TypeScript pools plus the Wikipedia metadata in `data/wiki-cache.json`.
 *
 *   npm run wiki:enrich   # fetch/refresh Wikipedia data (network)
 *   npm run seed:sql      # regenerate the migration (offline)
 *
 * The statement is an idempotent UPSERT, so re-running the migration after
 * adding or rebalancing characters updates rows in place and never disturbs
 * games already stored in the database.
 *
 * `0002_seed_characters.sql` is the frozen V1 seed and is deliberately left
 * alone — migration 0003 retires those rows rather than deleting them.
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { CHARACTERS } from "../src/lib/game/characters";
import { CATEGORIES, allAxes, getCategory } from "../src/lib/game/categories";
import type { WikiRecord } from "./enrich-characters";

const q = (s: string | null) =>
  s === null || s === undefined ? "null" : `'${s.replace(/'/g, "''")}'`;
const arr = (items: string[]) =>
  items.length ? `array[${items.map((i) => q(i)).join(", ")}]::text[]` : "'{}'::text[]";
const json = (value: unknown) => `'${JSON.stringify(value).replace(/'/g, "''")}'::jsonb`;

const cachePath = join(process.cwd(), "data", "wiki-cache.json");
const wiki: Record<string, WikiRecord> = existsSync(cachePath)
  ? (JSON.parse(readFileSync(cachePath, "utf8")) as Record<string, WikiRecord>)
  : {};

let withImage = 0;

const values = CHARACTERS.map((c) => {
  const w = wiki[c.id];
  const category = getCategory(c.categoryId);
  const axes = allAxes(category, c.stats);
  if (w?.thumbnailUrl) withImage++;

  // The V1 columns are NOT NULL and some tooling still reads them, so they are
  // kept in sync with the canonical axes rather than left to drift.
  const legacy = {
    power: Math.round(axes.power),
    speed: Math.round(axes.speed),
    defense: Math.round(axes.defense),
    tactics: Math.round(axes.strategy),
    special: Math.round(axes.special),
  };

  return `  (${[
    q(c.id),
    q(c.name),
    q(c.title),
    q(c.universe),
    q(c.rarity),
    q(c.categoryId),
    q(c.version),
    q(w?.description ?? c.description ?? ""),
    q(c.actor),
    json(c.stats),
    String(c.gamePower),
    arr(c.abilities),
    arr(c.tags),
    String(c.basePrice),
    q(w?.wikiTitle ?? c.wikiTitle),
    q(w?.wikiUrl ?? null),
    q(w?.imageUrl ?? null),
    q(w?.thumbnailUrl ?? null),
    q(w?.imageSource ?? null),
    q(w?.imageLicense ?? null),
    q(w?.imageCredit ?? null),
    arr(c.palette),
    "true",
    String(legacy.power),
    String(legacy.speed),
    String(legacy.defense),
    String(legacy.tactics),
    String(legacy.special),
    q(c.abilities[0] ?? ""),
  ].join(", ")})`;
}).join(",\n");

const sql = `-- AUTO-GENERATED by \`npm run seed:sql\`.
-- Source: src/lib/game/pools/*.ts + data/wiki-cache.json
-- Do not edit by hand: edit the pools, re-run the enrichment, regenerate.
--
-- ${CHARACTERS.length} characters across ${CATEGORIES.length} categories, ${withImage} with a
-- Wikimedia image. Characters with no freely-licensed image on Wikipedia keep a
-- null image and the UI draws a generated placeholder instead.

insert into characters
  (id, name, title, universe, rarity, category, version, description, actor,
   stats, game_power, abilities, tags, base_price,
   wiki_title, wiki_url, image_url, thumbnail_url,
   image_source, image_license, image_credit, palette, enabled,
   power, speed, defense, tactics, special, special_ability)
values
${values}
on conflict (id) do update set
  name = excluded.name, title = excluded.title, universe = excluded.universe,
  rarity = excluded.rarity, category = excluded.category, version = excluded.version,
  description = excluded.description, actor = excluded.actor,
  stats = excluded.stats, game_power = excluded.game_power,
  abilities = excluded.abilities, tags = excluded.tags, base_price = excluded.base_price,
  wiki_title = excluded.wiki_title, wiki_url = excluded.wiki_url,
  image_url = excluded.image_url, thumbnail_url = excluded.thumbnail_url,
  image_source = excluded.image_source, image_license = excluded.image_license,
  image_credit = excluded.image_credit, palette = excluded.palette,
  enabled = excluded.enabled,
  power = excluded.power, speed = excluded.speed, defense = excluded.defense,
  tactics = excluded.tactics, special = excluded.special,
  special_ability = excluded.special_ability;
`;

const out = join(process.cwd(), "supabase", "migrations", "0004_seed_v2_characters.sql");
writeFileSync(out, sql, "utf8");
console.log(
  `${CHARACTERS.length} karakter yazıldı (${withImage} görselli) -> ${out}`,
);
