/**
 * Regenerates `supabase/migrations/0002_seed_characters.sql` from the
 * TypeScript character pool, so the pool has exactly one source of truth.
 *
 *   npm run seed:sql
 *
 * The generated statement is an idempotent UPSERT: re-running the migration
 * after adding or rebalancing characters updates rows in place and never
 * disturbs games already stored in the database.
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { CHARACTERS } from "../src/lib/game/characters";

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;
const arr = (items: string[]) =>
  `array[${items.map((i) => q(i)).join(", ")}]::text[]`;

const values = CHARACTERS.map(
  (c) =>
    `  (${q(c.id)}, ${q(c.name)}, ${q(c.title)}, ${q(c.universe)}, ${q(c.rarity)}, ` +
    `${c.power}, ${c.speed}, ${c.defense}, ${c.tactics}, ${c.special}, ` +
    `${q(c.specialAbility)}, ${arr(c.tags)}, ${c.basePrice}, ` +
    `${c.imageUrl ? q(c.imageUrl) : "null"}, ${arr(c.palette)})`,
).join(",\n");

const sql = `-- AUTO-GENERATED by \`npm run seed:sql\` from src/lib/game/characters.ts
-- Do not edit by hand: edit the TypeScript pool and regenerate.

insert into characters
  (id, name, title, universe, rarity, power, speed, defense, tactics, special,
   special_ability, tags, base_price, image_url, palette)
values
${values}
on conflict (id) do update set
  name = excluded.name,
  title = excluded.title,
  universe = excluded.universe,
  rarity = excluded.rarity,
  power = excluded.power,
  speed = excluded.speed,
  defense = excluded.defense,
  tactics = excluded.tactics,
  special = excluded.special,
  special_ability = excluded.special_ability,
  tags = excluded.tags,
  base_price = excluded.base_price,
  image_url = excluded.image_url,
  palette = excluded.palette;
`;

const out = join(
  process.cwd(),
  "supabase",
  "migrations",
  "0002_seed_characters.sql",
);
writeFileSync(out, sql, "utf8");
console.log(`Wrote ${CHARACTERS.length} characters to ${out}`);
