-- AUTO-GENERATED by `npm run seed:sql` from src/lib/game/characters.ts
-- Do not edit by hand: edit the TypeScript pool and regenerate.

insert into characters
  (id, name, title, universe, rarity, power, speed, defense, tactics, special,
   special_ability, tags, base_price, image_url, palette)
values
  ('kane-vasco', 'Kane Vasco', 'The Ronin', 'ACTION', 'LEGENDARY', 88, 91, 82, 96, 94, 'Pencil Work', array['melee', 'marksman', 'tactical', 'stealth']::text[], 10, null, array['#7c3aed', '#22d3ee']::text[]),
  ('adam-kessler', 'Adam Kessler', 'The Erased Asset', 'ACTION', 'LEGENDARY', 82, 90, 84, 98, 92, 'Improvised Counter', array['tactical', 'stealth', 'brawler', 'survival']::text[], 10, null, array['#2563eb', '#38bdf8']::text[]),
  ('ryder-cross', 'Ryder Cross', 'Impossible Odds', 'ACTION', 'EPIC', 84, 93, 80, 94, 95, 'Rooftop Gambit', array['mobility', 'tactical', 'tech']::text[], 9, null, array['#f43f5e', '#fb923c']::text[]),
  ('sterling-vane', 'Sterling Vane', 'Crown Agent', 'ACTION', 'EPIC', 83, 86, 85, 97, 93, 'Gadget Play', array['tactical', 'marksman', 'tech', 'stealth']::text[], 9, null, array['#0ea5e9', '#a78bfa']::text[]),
  ('tyler-stone', 'Tyler Stone', 'The Extractor', 'ACTION', 'EPIC', 94, 85, 92, 82, 90, 'One-Shot Corridor', array['melee', 'ranged', 'survival', 'brawler']::text[], 9, null, array['#16a34a', '#84cc16']::text[]),
  ('boone-halloway', 'Boone Halloway', 'The Last Veteran', 'ACTION', 'EPIC', 95, 80, 95, 86, 88, 'Trap Line', array['survival', 'ranged', 'melee', 'veteran']::text[], 9, null, array['#65a30d', '#facc15']::text[]),
  ('frank-mercer', 'Frank Mercer', 'The Courier', 'ACTION', 'RARE', 86, 92, 86, 90, 89, 'Precision Delivery', array['mobility', 'melee', 'tactical']::text[], 8, null, array['#111827', '#f59e0b']::text[]),
  ('elias-quinn', 'Elias Quinn', 'The Bookkeeper', 'ACTION', 'EPIC', 87, 82, 90, 97, 88, 'Twenty-Nine Seconds', array['tactical', 'melee', 'stealth']::text[], 9, null, array['#334155', '#22d3ee']::text[]),
  ('bryce-kellan', 'Bryce Kellan', 'The Retriever', 'ACTION', 'RARE', 89, 84, 88, 95, 86, 'Particular Skills', array['tactical', 'marksman', 'veteran']::text[], 8, null, array['#7f1d1d', '#f87171']::text[]),
  ('kiri-amano', 'Kiri Amano', 'The Vowed Blade', 'ACTION', 'LEGENDARY', 88, 95, 78, 90, 93, 'Five Point Strike', array['melee', 'mobility', 'stealth']::text[], 10, null, array['#fbbf24', '#ef4444']::text[]),
  ('arka-wijaya', 'Arka Wijaya', 'Raid Fist', 'ACTION', 'EPIC', 92, 96, 82, 80, 93, 'Stairwell Rush', array['melee', 'brawler', 'mobility']::text[], 9, null, array['#dc2626', '#fde047']::text[]),
  ('cutter-braddock', 'Cutter Braddock', 'Jungle Command', 'ACTION', 'RARE', 96, 78, 94, 84, 90, 'Suppressing Fire', array['ranged', 'survival', 'leader', 'brawler']::text[], 8, null, array['#166534', '#a3e635']::text[]),
  ('cole-mateo', 'Cole Mateo', 'One Man Squad', 'ACTION', 'RARE', 98, 80, 95, 78, 91, 'Armory Dump', array['brawler', 'ranged', 'melee']::text[], 8, null, array['#b45309', '#fbbf24']::text[]),
  ('milo-reyes', 'Milo Reyes', 'The Cleaner', 'ACTION', 'EPIC', 80, 86, 82, 98, 96, 'Silent Setup', array['marksman', 'stealth', 'tactical']::text[], 9, null, array['#1e293b', '#4ade80']::text[]),
  ('nash-riggs', 'Nash Riggs', 'Adrenaline Case', 'ACTION', 'RARE', 93, 97, 74, 80, 98, 'Redline', array['mobility', 'brawler', 'melee']::text[], 8, null, array['#e11d48', '#f97316']::text[]),
  ('rook-calloway', 'Rook Calloway', 'The Escapist', 'ACTION', 'RARE', 90, 83, 88, 92, 89, 'Countdown Bluff', array['stealth', 'survival', 'ranged', 'leader']::text[], 8, null, array['#0f172a', '#38bdf8']::text[]),
  ('lin-bo', 'Master Lin Bo', 'Improvised Master', 'ACTION', 'EPIC', 84, 94, 84, 92, 89, 'Environmental Combat', array['melee', 'mobility', 'brawler', 'environment']::text[], 9, null, array['#f59e0b', '#ef4444']::text[]),
  ('wei-zhan', 'Wei Zhan', 'Iron Discipline', 'ACTION', 'RARE', 91, 93, 86, 86, 87, 'Wing Chun Chain', array['melee', 'brawler', 'mobility']::text[], 8, null, array['#1d4ed8', '#f8fafc']::text[]),
  ('dex-harlow', 'Dex Harlow', 'The Mechanic', 'ACTION', 'RARE', 92, 88, 89, 85, 88, 'Clean Exit', array['brawler', 'mobility', 'melee', 'ranged']::text[], 8, null, array['#475569', '#f43f5e']::text[]),
  ('viktor-sable', 'Viktor Sable', 'The Undisputed', 'ACTION', 'RARE', 93, 95, 85, 80, 89, 'Spinning Finish', array['melee', 'mobility', 'brawler']::text[], 8, null, array['#6d28d9', '#f472b6']::text[])
on conflict (id) do update set
  name = excluded.name,
  title = excluded.title,
  universe = excluded.universe,
  rarity = excluded.rarity,
  power = excluded.power,
  speed = excluded.speed,
  defense = excluded.defense,
  tactics = excluded.tactics,
  special = excluded.special,
  special_ability = excluded.special_ability,
  tags = excluded.tags,
  base_price = excluded.base_price,
  image_url = excluded.image_url,
  palette = excluded.palette;
