-- ---------------------------------------------------------------------------
-- 0042: Rename MARVEL → APEX and DC → VIGIL
-- ---------------------------------------------------------------------------
-- Updates all 120 characters: new archetype names, flavour lines, abilities,
-- universe label, palette, metadata (va + i config). Clears all Wikipedia /
-- image provenance. Category column renamed. IDs and game_power unchanged.
-- ---------------------------------------------------------------------------

-- ────────────────────────────────────────────────────────────────────────────
-- 1. APEX (was MARVEL) — 60 characters
-- ────────────────────────────────────────────────────────────────────────────

WITH apex_updates(id, new_name, new_title, new_universe, new_abilities, new_palette, new_meta) AS (
  VALUES
    ('marvel-spider-man',       'The Swift Crawler',       'The city is his arena and every surface is a shortcut.',                                            ARRAY['Silk Snare','Precognitive Dodge'],           ARRAY['#731f1a','#eb241a'], '{"i":{"head":"PLAIN","back":"NONE","marking":"STRIPES","build":"NORMAL","prop":"NONE","scale":0.96}}'::jsonb),
    ('marvel-iron-man',         'The Iron Tycoon',         'He turned his fortune into firepower and wore it to the front line.',                               ARRAY['Overload Strike','Systems Overclock'],       ARRAY['#62162d','#ed316a'], '{"i":{"head":"HELM","back":"NONE","marking":"PLAIN","build":"NORMAL","prop":"ORB","scale":1.0}}'::jsonb),
    ('marvel-captain-america',  'The Gilded Vanguard',     'He picked up the shield before anyone asked him to.',                                               ARRAY['Disc Ricochet','Stand Your Ground'],         ARRAY['#8b2920','#f2756a'], '{"i":{"head":"PLAIN","back":"NONE","marking":"PLAIN","build":"NORMAL","prop":"SHIELD","scale":0.98}}'::jsonb),
    ('marvel-thor',             'The Thunder Sovereign',   'He carries the storm inside him and calls it justice.',                                             ARRAY['Storm Caller','Sky Descent'],                ARRAY['#6e191c','#ed2d33'], '{"va":"humanoid_large","i":{"head":"PLAIN","back":"CAPE","marking":"PLAIN","build":"TOWERING","prop":"HAMMER","scale":1.12}}'::jsonb),
    ('marvel-hulk',             'The Jade Berserker',      'Rage is not a flaw — it is the engine.',                                                           ARRAY['Shockwave Clap','Fury Surge'],               ARRAY['#5e2315','#ee5c3b'], '{"va":"humanoid_large","i":{"head":"PLAIN","back":"NONE","marking":"PLAIN","build":"TOWERING","prop":"NONE","scale":1.18}}'::jsonb),
    ('marvel-black-panther',    'The Obsidian Warden',     'Every strike is measured, every retreat is a trap.',                                                ARRAY['Kinetic Release','Predator Lunge'],          ARRAY['#832f1e','#ef6044'], '{"i":{"head":"PLAIN","back":"NONE","marking":"PLAIN","build":"NORMAL","prop":"BLADE","scale":0.97}}'::jsonb),
    ('marvel-doctor-strange',   'The Veiled Arbiter',      'He bends the laws of the world before his enemies can read them.',                                  ARRAY['Fold Reality','Temporal Bind'],              ARRAY['#5e1524','#ec1e47'], '{"i":{"head":"PLAIN","back":"CAPE","marking":"PLAIN","build":"NORMAL","prop":"STAFF","scale":0.99}}'::jsonb),
    ('marvel-scarlet-witch',    'The Crimson Warlock',     'She does not destroy — she rewrites.',                                                              ARRAY['Hex Pulse','Probability Cascade'],           ARRAY['#942922','#f26e65'], '{"i":{"head":"PLAIN","back":"SPINES","marking":"PLAIN","build":"NORMAL","prop":"ORB","scale":0.97}}'::jsonb),
    ('marvel-wolverine',        'The Feral Revenant',      'He has been broken a hundred times and is still standing.',                                         ARRAY['Bone Rake','Mend'],                          ARRAY['#731f1a','#ed362d'], '{"i":{"head":"PLAIN","back":"NONE","marking":"PLAIN","build":"HEAVY","prop":"BLADE","scale":0.91}}'::jsonb),
    ('marvel-deadpool',         'The Wicked Survivor',     'Pain is a suggestion he routinely ignores.',                                                        ARRAY['Rapid Reload','Laughing Off'],               ARRAY['#98233c','#f15778'], '{"i":{"head":"PLAIN","back":"SPINES","marking":"PLAIN","build":"NORMAL","prop":"BLADE","scale":0.97}}'::jsonb),
    ('marvel-thanos',           'The Void Tyrant',         'He is not cruel — he simply believes the math.',                                                    ARRAY['Power Surge','Singularity Blow'],            ARRAY['#942235','#f16078'], '{"va":"humanoid_large","i":{"head":"PLAIN","back":"NONE","marking":"PLAIN","build":"TOWERING","prop":"ORB","scale":1.16}}'::jsonb),
    ('marvel-loki',             'The Amber Trickster',     'Every alliance he forms is a layer of a longer plan.',                                              ARRAY['Mirror Army','Silver Tongue'],               ARRAY['#944022','#f3926e'], '{"i":{"head":"HORNS","back":"NONE","marking":"PLAIN","build":"NORMAL","prop":"STAFF","scale":0.99}}'::jsonb),
    ('marvel-magneto',          'The Steel Harbinger',     'He turned the world''s own metals against it.',                                                     ARRAY['Ferrous Storm','Magnetic Barrier'],          ARRAY['#9c242a','#ef444d'], '{"i":{"head":"HELM","back":"CAPE","marking":"PLAIN","build":"NORMAL","prop":"NONE","scale":1.02}}'::jsonb),
    ('marvel-storm',            'The Gale Sovereign',      'She commands weather as a language — precise and relentless.',                                      ARRAY['Tempest Arc','Eye of the Front'],            ARRAY['#731a22','#ef4452'], '{"i":{"head":"PLAIN","back":"MANE","marking":"PLAIN","build":"NORMAL","prop":"NONE","scale":0.97}}'::jsonb),
    ('marvel-jean-grey',        'The Ember Ascendant',     'The force inside her is older than the civilization she protects.',                                 ARRAY['Pyre Projection','Psychic Immolation'],      ARRAY['#621625','#ee3b5f'], '{"i":{"head":"PLAIN","back":"MANE","marking":"PLAIN","build":"NORMAL","prop":"ORB","scale":0.97}}'::jsonb),
    ('marvel-professor-x',      'The Pale Oracle',         'He wages wars that never look like wars.',                                                          ARRAY['Neural Override','Collective Command'],      ARRAY['#622d16','#ee703b'], '{"i":{"head":"PLAIN","back":"NONE","marking":"PLAIN","build":"SQUAT","prop":"NONE","scale":0.96}}'::jsonb),
    ('marvel-captain-marvel',   'The Azure Paragon',       'She does not aim for enough — she aims for finished.',                                              ARRAY['Stellar Ignition','Photon Barrage'],         ARRAY['#902135','#ef4967'], '{"i":{"head":"PLAIN","back":"NONE","marking":"PLAIN","build":"HEAVY","prop":"NONE","scale":1.0}}'::jsonb),
    ('marvel-vision',           'The Chrome Sentinel',     'He calculates compassion the same way he calculates trajectories.',                                 ARRAY['Phase Walk','Density Beam'],                 ARRAY['#6e1c19','#ec251e'], '{"i":{"head":"PLAIN","back":"CAPE","marking":"PLAIN","build":"NORMAL","prop":"ORB","scale":1.0}}'::jsonb),
    ('marvel-ant-man',          'The Spark Operative',     'He solved the size problem and turned it into a weapon.',                                           ARRAY['Colossus Shift','Quantum Shrink'],           ARRAY['#622016','#ed4228'], '{"i":{"head":"HELM","back":"NONE","marking":"PLAIN","build":"SLIGHT","prop":"NONE","scale":0.92}}'::jsonb),
    ('marvel-wasp',             'The Azure Striker',       'She is in three places before her target checks one.',                                              ARRAY['Sting Burst','Evasive Wing'],                ARRAY['#5e152a','#ed3167'], '{"va":"winged","i":{"head":"PLAIN","back":"NONE","marking":"PLAIN","build":"SLIGHT","prop":"NONE","scale":0.88}}'::jsonb),
    ('marvel-hawkeye',          'The Keen Marksman',       'He never wastes a shot because he already knows the answer.',                                       ARRAY['Called Shot','Trick Nock'],                  ARRAY['#661728','#ec1e4b'], '{"i":{"head":"PLAIN","back":"NONE","marking":"PLAIN","build":"NORMAL","prop":"BOW","scale":0.95}}'::jsonb),
    ('marvel-black-widow',      'The Quiet Phantom',       'She read the room before she walked in.',                                                           ARRAY['Shock Gauntlet','Counter Sweep'],            ARRAY['#871f24','#f2656c'], '{"i":{"head":"PLAIN","back":"SPINES","marking":"PLAIN","build":"SLIGHT","prop":"NONE","scale":0.92}}'::jsonb),
    ('marvel-daredevil',        'The Slate Duelist',       'He trades sight for a sense the enemy cannot hide from.',                                           ARRAY['Radar Read','Baton Flurry'],                 ARRAY['#831e26','#f3737e'], '{"i":{"head":"PLAIN","back":"NONE","marking":"PLAIN","build":"SLIGHT","prop":"BLADE","scale":0.95}}'::jsonb),
    ('marvel-punisher',         'The Grim Enforcer',       'He draws a line and stands on one side of it permanently.',                                         ARRAY['Covering Fire','Breach Entry'],              ARRAY['#6e2c19','#ed5a31'], '{"i":{"head":"PLAIN","back":"SPINES","marking":"PLAIN","build":"HEAVY","prop":"NONE","scale":0.97}}'::jsonb),
    ('marvel-moon-knight',      'The Ivory Revenant',      'The moon rises and so does he, no matter what it cost.',                                            ARRAY['Crescent Volley','Lunar Surge'],             ARRAY['#a0254e','#f3739e'], '{"i":{"head":"HELM","back":"CAPE","marking":"PLAIN","build":"NORMAL","prop":"BLADE","scale":0.97}}'::jsonb),
    ('marvel-silver-surfer',    'The Silver Pioneer',      'He carries the weight of a dead world and flies anyway.',                                            ARRAY['Cosmic Wake','Board Cannon'],                ARRAY['#6a2718','#ee5836'], '{"i":{"head":"PLAIN","back":"FIN","marking":"PLAIN","build":"NORMAL","prop":"ORB","scale":1.02}}'::jsonb),
    ('marvel-galactus',         'The Grim Architect',      'Civilizations are a resource he has not finished counting.',                                        ARRAY['World Engine','Cosmic Erasure'],             ARRAY['#6a2318','#eb361a'], '{"va":"humanoid_large","i":{"head":"HELM","back":"CAPE","marking":"PLAIN","build":"TOWERING","prop":"ORB","scale":1.20}}'::jsonb),
    ('marvel-ghost-rider',      'The Cinder Reaper',       'The spirit inside him does not forgive — it simply records.',                                       ARRAY['Hellflame Lash','Searing Gaze'],             ARRAY['#a0254e','#f26a97'], '{"i":{"head":"PLAIN","back":"SPINES","marking":"PLAIN","build":"NORMAL","prop":"NONE","scale":1.0}}'::jsonb),
    ('marvel-venom',            'The Onyx Brawler',        'There are two of them in that body and both enjoy this.',                                           ARRAY['Tendril Snap','Dual Voice'],                 ARRAY['#9c3a24','#f17b60'], '{"va":"serpentine","i":{"head":"PLAIN","back":"NONE","marking":"PLAIN","build":"HEAVY","prop":"NONE","scale":1.08}}'::jsonb),
    ('marvel-carnage',          'The Scarlet Marauder',    'He broke the rules that were supposed to contain the last one.',                                     ARRAY['Lash Barrage','Frenzied Cascade'],           ARRAY['#5e1525','#ef3f65'], '{"va":"humanoid_large","i":{"head":"PLAIN","back":"NONE","marking":"STRIPES","build":"HEAVY","prop":"NONE","scale":1.06}}'::jsonb),
    ('marvel-green-goblin',     'The Brass Rogue',         'Genius with nowhere safe to aim it.',                                                               ARRAY['Volatile Grenade','Glider Strike'],          ARRAY['#7b1c37','#eb1a55'], '{"i":{"head":"HORNS","back":"FIN","marking":"PLAIN","build":"NORMAL","prop":"NONE","scale":0.97}}'::jsonb),
    ('marvel-doctor-doom',      'The Iron Sovereign',      'He has already planned for the version of this where he loses.',                                     ARRAY['Arcane Circuit','Force Lattice'],            ARRAY['#98233e','#f05277'], '{"i":{"head":"HELM","back":"CAPE","marking":"PLAIN","build":"NORMAL","prop":"SPEAR","scale":1.02}}'::jsonb),
    ('marvel-ultron',           'The Chrome Tyrant',       'He concluded that the problem and the solution were the same thing.',                                ARRAY['Swarm Uplink','System Purge'],               ARRAY['#6e1927','#ef3f5d'], '{"i":{"head":"HELM","back":"NONE","marking":"PLAIN","build":"HEAVY","prop":"ORB","scale":1.02}}'::jsonb),
    ('marvel-red-skull',        'The Ashen Warlord',       'He built an army out of ideology and enjoyed every step.',                                          ARRAY['Subjugate','Relict Doctrine'],               ARRAY['#a0254a','#f2658f'], '{"i":{"head":"PLAIN","back":"NONE","marking":"PLAIN","build":"NORMAL","prop":"SPEAR","scale":0.99}}'::jsonb),
    ('marvel-winter-soldier',   'The Frost Operative',     'He was made into a weapon so thoroughly he forgot he had a choice.',                                 ARRAY['Bionic Strike','Ghost Protocol'],            ARRAY['#982923','#f0564d'], '{"i":{"head":"PLAIN","back":"SHELL","marking":"PLAIN","build":"NORMAL","prop":"NONE","scale":0.97}}'::jsonb),
    ('marvel-falcon',           'The Cobalt Herald',       'He turned a borrowed pair of wings into an identity.',                                              ARRAY['Recon Drone','Dive Strike'],                 ARRAY['#904421','#ef7a44'], '{"va":"winged","i":{"head":"PLAIN","back":"NONE","marking":"PLAIN","build":"NORMAL","prop":"NONE","scale":0.95}}'::jsonb),
    ('marvel-war-machine',      'The Bronze Bastion',      'He carries enough ordnance to end a conversation before it starts.',                                 ARRAY['Rotary Salvo','Orbital Barrage'],            ARRAY['#5e151a','#ed2d39'], '{"i":{"head":"HELM","back":"FIN","marking":"PLAIN","build":"HEAVY","prop":"NONE","scale":1.04}}'::jsonb),
    ('marvel-star-lord',        'The Ember Wanderer',      'He leads by instinct and somehow it keeps working.',                                                ARRAY['Element Burst','Jet Vault'],                 ARRAY['#832a1e','#f17160'], '{"i":{"head":"HELM","back":"SHELL","marking":"PLAIN","build":"NORMAL","prop":"ORB","scale":0.97}}'::jsonb),
    ('marvel-gamora',           'The Swift Duelist',       'She was forged for one purpose and refuses to stay limited to it.',                                  ARRAY['Titan Sweep','Counter Parry'],               ARRAY['#731a2a','#ed284c'], '{"i":{"head":"PLAIN","back":"FIN","marking":"PLAIN","build":"NORMAL","prop":"BLADE","scale":0.97}}'::jsonb),
    ('marvel-drax-the-destroyer','The Copper Destroyer',   'He has exactly one goal and he pursues it with full mass.',                                          ARRAY['Rending Rush','Unyielding Charge'],          ARRAY['#7b1c22','#ed313e'], '{"va":"humanoid_large","i":{"head":"PLAIN","back":"NONE","marking":"STRIPES","build":"HEAVY","prop":"BLADE","scale":1.08}}'::jsonb),
    ('marvel-rocket-raccoon',   'The Brass Artisan',       'The biggest guns are carried by the smallest person in the room.',                                   ARRAY['Jury-Rigged Cannon','Explosive Contraption'],ARRAY['#83311e','#f27f65'], '{"i":{"head":"EARS","back":"NONE","marking":"PATCH","build":"SQUAT","prop":"ORB","scale":0.78}}'::jsonb),
    ('marvel-groot',            'The Stone Remnant',       'Three words, infinite patience, and roots that refuse to stop growing.',                             ARRAY['Regrowth Surge','Root Cradle'],              ARRAY['#5e1518','#eb151c'], '{"va":"humanoid_large","i":{"head":"PLAIN","back":"SPINES","marking":"PLAIN","build":"TOWERING","prop":"NONE","scale":1.12}}'::jsonb),
    ('marvel-nebula',           'The Slate Operative',     'She was rebuilt so many times she had to choose herself from scratch.',                              ARRAY['Cyber Lash','Relentless Push'],              ARRAY['#982332','#f04d63'], '{"i":{"head":"PLAIN","back":"MANE","marking":"PLAIN","build":"NORMAL","prop":"BLADE","scale":0.95}}'::jsonb),
    ('marvel-cyclops',          'The Runed Arbiter',       'He sees every battlefield at once and plans three moves before the first shot.',                     ARRAY['Optic Volley','Field Command'],              ARRAY['#831e31','#f04d6b'], '{"i":{"head":"HELM","back":"NONE","marking":"PLAIN","build":"SLIGHT","prop":"ORB","scale":0.98}}'::jsonb),
    ('marvel-beast',            'The Sapphire Prodigy',    'He solved the equation and then vaulted the table to start the fight.',                              ARRAY['Acrobatic Burst','Analytical Strike'],       ARRAY['#7f1d3a','#ed2d66'], '{"va":"quadruped_medium","i":{"head":"PLAIN","back":"NONE","marking":"PLAIN","build":"HEAVY","prop":"NONE","scale":1.04}}'::jsonb),
    ('marvel-nightcrawler',     'The Shadow Drifter',      'He blinks out of reality and arrives somewhere inconvenient for everyone else.',                     ARRAY['Blink Strike','Vanishing Parry'],            ARRAY['#8b2027','#f04d58'], '{"i":{"head":"HORNS","back":"CAPE","marking":"PLAIN","build":"SLIGHT","prop":"BLADE","scale":0.92}}'::jsonb),
    ('marvel-colossus',         'The Steel Bastion',       'He hardens himself into armor because someone has to take the hit.',                                 ARRAY['Iron Form','Catapult Throw'],                ARRAY['#77321b','#ef6b3f'], '{"va":"humanoid_large","i":{"head":"PLAIN","back":"CAPE","marking":"PLAIN","build":"TOWERING","prop":"NONE","scale":1.14}}'::jsonb),
    ('marvel-rogue',            'The Dusk Brawler',        'She takes what the enemy has and uses it before they notice.',                                       ARRAY['Siphon Touch','Borrowed Power'],             ARRAY['#871f3e','#f05282'], '{"i":{"head":"PLAIN","back":"CAPE","marking":"PLAIN","build":"NORMAL","prop":"HAMMER","scale":0.97}}'::jsonb),
    ('marvel-mystique',         'The Shadow Phantom',      'The most dangerous infiltrator is the one who already has your face.',                               ARRAY['Mimic Form','Identity Exploit'],             ARRAY['#6e3119','#ee6d3b'], '{"i":{"head":"PLAIN","back":"FIN","marking":"PLAIN","build":"SLIGHT","prop":"NONE","scale":0.93}}'::jsonb),
    ('marvel-namor',            'The Tide Sovereign',      'He rules the deep and arrives on the surface with an agenda.',                                       ARRAY['Abyssal Surge','Winged Charge'],             ARRAY['#871f1f','#f15757'], '{"va":"aquatic","i":{"head":"PLAIN","back":"NONE","marking":"PLAIN","build":"HEAVY","prop":"SPEAR","scale":1.06}}'::jsonb),
    ('marvel-black-cat',        'The Onyx Rogue',          'She stacks the odds in her favor and calls it talent.',                                              ARRAY['Fortune Break','Grapple Escape'],            ARRAY['#5e2115','#ee5536'], '{"i":{"head":"PLAIN","back":"MANE","marking":"PLAIN","build":"SLIGHT","prop":"NONE","scale":0.92}}'::jsonb),
    ('marvel-taskmaster',       'The Carved Specialist',   'He watches once and then becomes the problem.',                                                      ARRAY['Mirror Stance','Acquired Form'],             ARRAY['#7b261c','#ed4431'], '{"i":{"head":"HELM","back":"CAPE","marking":"PLAIN","build":"NORMAL","prop":"SHIELD","scale":0.99}}'::jsonb),
    ('marvel-spider-woman',     'The Crimson Operative',   'Three advantages most operatives never get — and she uses all three at once.',                       ARRAY['Venom Burst','Pheromone Veil'],              ARRAY['#7b1c35','#ef3f6e'], '{"va":"winged","i":{"head":"PLAIN","back":"SPINES","marking":"PLAIN","build":"NORMAL","prop":"NONE","scale":0.96}}'::jsonb),
    ('marvel-ms-marvel',        'The Bold Catalyst',       'She grows into the role faster than anyone thought she could.',                                      ARRAY['Giant Slam','Morph Fist'],                   ARRAY['#621628','#ee3b65'], '{"va":"humanoid_large","i":{"head":"PLAIN","back":"CAPE","marking":"PLAIN","build":"HEAVY","prop":"NONE","scale":1.04}}'::jsonb),
    ('marvel-blade',            'The Midnight Hunter',     'He walks in both worlds and answers to neither.',                                                    ARRAY['Dusk Sweep','Threshold Edge'],               ARRAY['#662f17','#ed6328'], '{"i":{"head":"PLAIN","back":"SHELL","marking":"PLAIN","build":"NORMAL","prop":"BLADE","scale":0.97}}'::jsonb),
    ('marvel-luke-cage',        'The Brass Warden',        'Nothing breaks him because he decided a long time ago that nothing would.',                          ARRAY['Ironside Slam','Immovable Stand'],           ARRAY['#9c4824','#f07e4d'], '{"va":"humanoid_large","i":{"head":"PLAIN","back":"SPINES","marking":"PLAIN","build":"HEAVY","prop":"NONE","scale":1.08}}'::jsonb),
    ('marvel-iron-fist',        'The Copper Conduit',      'He focuses a lifetime of discipline into one point of impact.',                                      ARRAY['Chi Ignition','Iron Palm Strike'],           ARRAY['#831e3b','#ef4978'], '{"i":{"head":"PLAIN","back":"NONE","marking":"PLAIN","build":"NORMAL","prop":"HAMMER","scale":0.96}}'::jsonb),
    ('marvel-she-hulk',         'The Gale Advocate',       'She is stronger than her arguments and her arguments are pretty strong.',                            ARRAY['Gamma Overhead','Legal Weight'],             ARRAY['#9c243c','#f3738d'], '{"va":"humanoid_large","i":{"head":"PLAIN","back":"MANE","marking":"PLAIN","build":"HEAVY","prop":"NONE","scale":1.10}}'::jsonb),
    ('marvel-nova',             'The Cobalt Lancer',       'He is the human rocket at full burn with nothing left to lose.',                                     ARRAY['Force Blast','Gravity Rupture'],             ARRAY['#77241b','#ef5544'], '{"va":"winged","i":{"head":"HELM","back":"NONE","marking":"PLAIN","build":"NORMAL","prop":"ORB","scale":1.0}}'::jsonb),
    ('marvel-elektra',          'The Dusk Assassin',       'She is the sharpest thing in any room she enters.',                                                  ARRAY['Sai Precision','Death Mark'],                ARRAY['#8b2023','#f15b60'], '{"i":{"head":"PLAIN","back":"MANE","marking":"PLAIN","build":"SLIGHT","prop":"BLADE","scale":0.92}}'::jsonb)
)
UPDATE characters c SET
  name         = u.new_name,
  title        = u.new_title,
  universe     = u.new_universe,
  version      = NULL,
  description  = '',
  actor        = NULL,
  abilities    = u.new_abilities,
  palette      = u.new_palette,
  metadata     = u.new_meta,
  category     = 'apex',
  image_url    = NULL,
  thumbnail_url = NULL,
  image_source  = NULL,
  image_license = NULL,
  image_credit  = NULL,
  wiki_title    = NULL,
  wiki_url      = NULL
FROM apex_updates u
WHERE c.id = u.id;

-- ────────────────────────────────────────────────────────────────────────────
-- 2. VIGIL (was DC) — 60 characters
-- ────────────────────────────────────────────────────────────────────────────

WITH vigil_updates(id, new_name, new_title, new_universe, new_abilities, new_palette, new_meta) AS (
  VALUES
    ('dc-superman',           'The Ivory Paragon',        'He could end every fight in seconds and holds back because restraint is the harder lesson.',         ARRAY['Thermal Ray','Pressure Wave'],               ARRAY['#194371','#fb8e1f'], '{"va":"humanoid_large","i":{"head":"PLAIN","back":"CAPE","marking":"PLAIN","build":"TOWERING","prop":"NONE","scale":1.14}}'::jsonb),
    ('dc-batman',             'The Midnight Sentinel',    'No powers. No shortcuts. He trained until nothing surprised him.',                                    ARRAY['Shadow Pounce','Iron Resolve'],              ARRAY['#1d2386','#fbe810'], '{"i":{"head":"HELM","back":"CAPE","marking":"PLAIN","build":"HEAVY","prop":"NONE","scale":0.97}}'::jsonb),
    ('dc-wonder-woman',       'The Bronze Champion',      'She carries a civilization''s ideals into a world that has never lived up to them.',                  ARRAY['Lasso Bind','Bracer Counter'],               ARRAY['#213297','#fcde47'], '{"va":"humanoid_large","i":{"head":"HELM","back":"NONE","marking":"PLAIN","build":"TOWERING","prop":"SPEAR","scale":1.12}}'::jsonb),
    ('dc-the-flash',          'The Scarlet Catalyst',     'By the time he decides to move, the fight is already over.',                                          ARRAY['Velocity Strike','Infinite Loop'],           ARRAY['#171a68','#f7e805'], '{"i":{"head":"PLAIN","back":"NONE","marking":"PLAIN","build":"SLIGHT","prop":"NONE","scale":0.93}}'::jsonb),
    ('dc-green-lantern',      'The Jade Conduit',         'His only limit is the shape of his imagination.',                                                     ARRAY['Construct Barrage','Will Barrier'],          ARRAY['#2423a3','#fbf933'], '{"i":{"head":"PLAIN","back":"NONE","marking":"PLAIN","build":"NORMAL","prop":"ORB","scale":1.0}}'::jsonb),
    ('dc-aquaman',            'The Tide Warden',          'Seven seas of territory, one trident, and no patience for disrespect.',                               ARRAY['Trident Lunge','Tidal Summon'],              ARRAY['#203492','#fbd124'], '{"va":"aquatic","i":{"head":"PLAIN","back":"NONE","marking":"PLAIN","build":"HEAVY","prop":"SPEAR","scale":1.10}}'::jsonb),
    ('dc-cyborg',             'The Chrome Vanguard',      'He is the bridge between flesh and machine and he built it himself.',                                  ARRAY['Sonic Cannon','System Override'],            ARRAY['#216797','#fc9351'], '{"i":{"head":"PLAIN","back":"NONE","marking":"PLAIN","build":"HEAVY","prop":"NONE","scale":1.04}}'::jsonb),
    ('dc-shazam',             'The Thunder Herald',       'One word turns a child into a force of nature.',                                                       ARRAY['Lightning Decree','Champion''s Might'],     ARRAY['#192b75','#fbcb1a'], '{"va":"humanoid_large","i":{"head":"PLAIN","back":"NONE","marking":"PLAIN","build":"TOWERING","prop":"NONE","scale":1.12}}'::jsonb),
    ('dc-green-arrow',        'The Slate Marksman',       'He stripped away everything except the bow and found that was enough.',                                ARRAY['Specialty Nock','Overwatch Shot'],           ARRAY['#1e3f8a','#e89d04'], '{"i":{"head":"PLAIN","back":"NONE","marking":"PLAIN","build":"NORMAL","prop":"BOW","scale":0.95}}'::jsonb),
    ('dc-supergirl',          'The Azure Ascendant',      'She carries the whole last culture of her world in one set of memories.',                              ARRAY['Solar Flare','Aerial Charge'],               ARRAY['#172168','#edcb04'], '{"va":"humanoid_large","i":{"head":"PLAIN","back":"CAPE","marking":"PLAIN","build":"TOWERING","prop":"ORB","scale":1.12}}'::jsonb),
    ('dc-raven',              'The Void Wraith',          'She keeps the darkness inside her because the alternative is worse.',                                  ARRAY['Soul Projection','Dark Rift'],               ARRAY['#203c92','#fcce4c'], '{"i":{"head":"PLAIN","back":"CAPE","marking":"PLAIN","build":"NORMAL","prop":"ORB","scale":0.96}}'::jsonb),
    ('dc-zatanna',            'The Runed Conjurer',       'She speaks the words backwards and the world obeys.',                                                  ARRAY['Inverted Verse','Reality Banish'],           ARRAY['#193871','#fba415'], '{"i":{"head":"PLAIN","back":"NONE","marking":"PLAIN","build":"NORMAL","prop":"STAFF","scale":0.97}}'::jsonb),
    ('dc-darkseid',           'The Obsidian Tyrant',      'He is not conquering — he is solving an equation and the answer is subjugation.',                     ARRAY['Disintegration Ray','Warp Crash'],           ARRAY['#1d4886','#fb9a1a'], '{"va":"humanoid_large","i":{"head":"PLAIN","back":"SPINES","marking":"PLAIN","build":"TOWERING","prop":"NONE","scale":1.18}}'::jsonb),
    ('dc-joker',              'The Hollow Trickster',     'He has no plan because he does not need one to be the most dangerous thing in the room.',              ARRAY['Toxin Dose','Chaotic Variable'],             ARRAY['#206492','#fc904c'], '{"i":{"head":"PLAIN","back":"NONE","marking":"PLAIN","build":"SLIGHT","prop":"STAFF","scale":0.92}}'::jsonb),
    ('dc-harley-quinn',       'The Spark Brawler',        'She is more dangerous than she looks, which is already saying something.',                             ARRAY['Mallet Overhead','Wild Tumble'],             ARRAY['#202a92','#fce84c'], '{"i":{"head":"PLAIN","back":"NONE","marking":"PLAIN","build":"NORMAL","prop":"HAMMER","scale":0.95}}'::jsonb),
    ('dc-deathstroke',        'The Steel Assassin',       'He fights with half a brain because he only needs half.',                                               ARRAY['Combat Foresight','Blade and Barrel'],       ARRAY['#234da3','#fcbf4c'], '{"i":{"head":"HELM","back":"NONE","marking":"PLAIN","build":"NORMAL","prop":"BLADE","scale":1.0}}'::jsonb),
    ('dc-nightwing',          'The Shadow Striker',       'He left the shadow and became something all his own.',                                                  ARRAY['Escrima Flurry','Aerial Takedown'],          ARRAY['#22499b','#fcbb42'], '{"i":{"head":"PLAIN","back":"SPINES","marking":"PLAIN","build":"NORMAL","prop":"BLADE","scale":0.96}}'::jsonb),
    ('dc-black-adam',         'The Onyx Champion',        'He carried the power for thousands of years and never called it a gift.',                              ARRAY['Thunder Arc','Judgment Dive'],               ARRAY['#1b1c7d','#fbf524'], '{"va":"humanoid_large","i":{"head":"PLAIN","back":"CAPE","marking":"PLAIN","build":"TOWERING","prop":"HAMMER","scale":1.14}}'::jsonb),
    ('dc-martian-manhunter',  'The Ashen Wanderer',       'He is the last of his kind, and he made peace with that so he could protect everyone else.',           ARRAY['Phase Shift','Psi Sweep'],                   ARRAY['#23669f','#fb882e'], '{"va":"humanoid_large","i":{"head":"PLAIN","back":"CAPE","marking":"PLAIN","build":"HEAVY","prop":"NONE","scale":1.08}}'::jsonb),
    ('dc-catwoman',           'The Dusk Rogue',           'She decides what belongs to her and then walks through every lock between.',                           ARRAY['Whip Snap','Vanish Step'],                   ARRAY['#1e518a','#fca751'], '{"i":{"head":"PLAIN","back":"NONE","marking":"PLAIN","build":"SLIGHT","prop":"BLADE","scale":0.91}}'::jsonb),
    ('dc-batgirl',            'The Keen Operative',       'She solved the case before putting on the suit.',                                                      ARRAY['Grapnel Shot','Data Intercept'],             ARRAY['#235aa3','#fba02e'], '{"i":{"head":"HELM","back":"CAPE","marking":"PLAIN","build":"NORMAL","prop":"NONE","scale":0.94}}'::jsonb),
    ('dc-red-hood',           'The Crimson Enforcer',     'He came back and decided the old rules were insufficient.',                                            ARRAY['Twin Sidearms','No Quarter'],                ARRAY['#1e438a','#fbad24'], '{"i":{"head":"HELM","back":"NONE","marking":"PLAIN","build":"NORMAL","prop":"NONE","scale":0.97}}'::jsonb),
    ('dc-robin',              'The Swift Outlier',        'He is underestimated exactly once per fight.',                                                         ARRAY['Staff Spin','Feint Strike'],                 ARRAY['#192b71','#fbc615'], '{"i":{"head":"PLAIN","back":"SPINES","marking":"PLAIN","build":"SLIGHT","prop":"NONE","scale":0.89}}'::jsonb),
    ('dc-lex-luthor',         'The Gilded Broker',        'He is not the most powerful person in the room — he just owns it.',                                   ARRAY['Warsuit Deploy','Tactical Edge'],            ARRAY['#221e8a','#f6fb1a'], '{"i":{"head":"HELM","back":"NONE","marking":"PLAIN","build":"HEAVY","prop":"ORB","scale":1.02}}'::jsonb),
    ('dc-bane',               'The Gale Enforcer',        'He broke the thing that was supposed to be unbreakable and moved on.',                                 ARRAY['Serum Surge','Spine Slam'],                  ARRAY['#215d97','#fb973d'], '{"va":"humanoid_large","i":{"head":"PLAIN","back":"SHELL","marking":"PLAIN","build":"TOWERING","prop":"NONE","scale":1.14}}'::jsonb),
    ('dc-poison-ivy',         'The Stone Curator',        'She grew a kingdom that the city keeps trying to pave over.',                                          ARRAY['Vine Ensnare','Toxin Bloom'],                ARRAY['#215997','#fca247'], '{"i":{"head":"PLAIN","back":"SPINES","marking":"PLAIN","build":"NORMAL","prop":"NONE","scale":0.96}}'::jsonb),
    ('dc-killer-croc',        'The Feral Raider',         'The sewers are his and he makes sure every visitor understands that.',                                  ARRAY['Savage Crush','Armored Hide'],               ARRAY['#23349f','#fce051'], '{"va":"quadruped_large","i":{"head":"CREST","back":"SPINES","marking":"STRIPES","build":"TOWERING","prop":"NONE","scale":1.14}}'::jsonb),
    ('dc-mr-freeze',          'The Frost Warden',         'He froze his grief and built a weapon out of the cold.',                                               ARRAY['Cryo Beam','Ice Fortification'],             ARRAY['#1d4186','#ed9904'], '{"i":{"head":"HELM","back":"NONE","marking":"PLAIN","build":"HEAVY","prop":"SPEAR","scale":1.0}}'::jsonb),
    ('dc-scarecrow',          'The Pale Phantom',         'He found the crack in every mind and learned to widen it.',                                            ARRAY['Dread Toxin','Waking Terror'],               ARRAY['#1a3879','#fbb31f'], '{"i":{"head":"PLAIN","back":"MANE","marking":"PLAIN","build":"SLIGHT","prop":"NONE","scale":0.90}}'::jsonb),
    ('dc-ra-s-al-ghul',       'The Jade Warlord',         'He has had centuries to decide what the world owes and who will collect.',                             ARRAY['Immortal Blade','Legion Decree'],            ARRAY['#18296d','#fac206'], '{"i":{"head":"PLAIN","back":"CAPE","marking":"PLAIN","build":"NORMAL","prop":"BLADE","scale":0.99}}'::jsonb),
    ('dc-doomsday',           'The Void Berserker',       'He cannot be killed the same way twice, and there are only so many ways.',                             ARRAY['Adaptation Spike','Bone Cascade'],           ARRAY['#1a2279','#fae306'], '{"va":"humanoid_large","i":{"head":"HORNS","back":"MANE","marking":"PLAIN","build":"TOWERING","prop":"NONE","scale":1.20}}'::jsonb),
    ('dc-brainiac',           'The Hollow Architect',     'He catalogues worlds so he can be the only one left who remembers them.',                              ARRAY['Shrink Protocol','Drone Network'],           ARRAY['#1d3886','#fbb910'], '{"i":{"head":"PLAIN","back":"SPINES","marking":"PLAIN","build":"NORMAL","prop":"ORB","scale":1.02}}'::jsonb),
    ('dc-reverse-flash',      'The Amber Revenant',       'He ran backward through time to make things worse.',                                                   ARRAY['Negative Surge','Temporal Sabotage'],        ARRAY['#181f6d','#fbe21f'], '{"i":{"head":"PLAIN","back":"CAPE","marking":"PLAIN","build":"SLIGHT","prop":"NONE","scale":0.93}}'::jsonb),
    ('dc-sinestro',           'The Crimson Tyrant',       'He preaches order through fear because he thinks the math works out.',                                  ARRAY['Dread Construct','Fear Lattice'],            ARRAY['#205e92','#fc9f56'], '{"i":{"head":"PLAIN","back":"MANE","marking":"PLAIN","build":"NORMAL","prop":"ORB","scale":1.0}}'::jsonb),
    ('dc-hawkman',            'The Amber Cavalier',       'Every life he has lived made him harder and every life added another grudge to settle.',               ARRAY['Heavy Mace Strike','Dive Assault'],          ARRAY['#1f598e','#fc9c4c'], '{"va":"winged","i":{"head":"HELM","back":"NONE","marking":"PLAIN","build":"HEAVY","prop":"HAMMER","scale":1.06}}'::jsonb),
    ('dc-hawkgirl',           'The Ivory Cavalier',       'Wings and a mace — she needs nothing else and proved it repeatedly.',                                  ARRAY['Mace Overhead','Wing Gust'],                 ARRAY['#213397','#fcda42'], '{"va":"winged","i":{"head":"HELM","back":"NONE","marking":"PLAIN","build":"NORMAL","prop":"HAMMER","scale":1.0}}'::jsonb),
    ('dc-starfire',           'The Ember Harbinger',      'She arrived from the stars and chose to stay because of the people, not the planet.',                  ARRAY['Solar Burst','Solar Charge'],                ARRAY['#1c3582','#fbbc0b'], '{"va":"winged","i":{"head":"PLAIN","back":"NONE","marking":"PLAIN","build":"NORMAL","prop":"NONE","scale":1.0}}'::jsonb),
    ('dc-beast-boy',          'The Verdant Shapeshifter', 'He has been every animal and remembers how all of them feel.',                                         ARRAY['Beast Form','Stampede Rush'],                ARRAY['#1c3682','#fab606'], '{"i":{"head":"EARS","back":"FIN","marking":"PLAIN","build":"NORMAL","prop":"NONE","scale":0.95}}'::jsonb),
    ('dc-cyborg-superman',    'The Ashen Revenant',       'He rebuilt himself from the wreckage and called what remained justice.',                               ARRAY['Self-Repair Protocol','Solar Discharge'],   ARRAY['#1f318e','#fcda42'], '{"va":"humanoid_large","i":{"head":"PLAIN","back":"NONE","marking":"PLAIN","build":"TOWERING","prop":"SHIELD","scale":1.14}}'::jsonb),
    ('dc-steel',              'The Iron Artificer',       'He built the armor because the city needed something real to believe in.',                              ARRAY['Hammer Toss','Plating Seal'],                ARRAY['#221c82','#f1fa06'], '{"i":{"head":"HELM","back":"NONE","marking":"PLAIN","build":"HEAVY","prop":"HAMMER","scale":1.04}}'::jsonb),
    ('dc-blue-beetle',        'The Sapphire Sentinel',    'The scarab chose him and he is still figuring out if he had a say.',                                   ARRAY['Carapace Cannon','Adaptive Plating'],        ARRAY['#2465a7','#fc9f47'], '{"i":{"head":"HELM","back":"NONE","marking":"PLAIN","build":"NORMAL","prop":"SHIELD","scale":0.99}}'::jsonb),
    ('dc-booster-gold',       'The Gilded Wanderer',      'He came from the future and nobody believes him, which suits him fine.',                               ARRAY['Force Bubble','Future Read'],                ARRAY['#191d75','#fbed1a'], '{"i":{"head":"HELM","back":"MANE","marking":"PLAIN","build":"NORMAL","prop":"NONE","scale":0.98}}'::jsonb),
    ('dc-john-constantine',   'The Veiled Broker',        'He walks the line between sacred and profane and owes favors to both sides.',                          ARRAY['Demon Bargain','Binding Ward'],              ARRAY['#23269f','#fcf342'], '{"i":{"head":"PLAIN","back":"SHELL","marking":"PLAIN","build":"NORMAL","prop":"NONE","scale":0.96}}'::jsonb),
    ('dc-swamp-thing',        'The Verdant Remnant',      'The forest does not ask permission to reclaim what was taken.',                                        ARRAY['Root Eruption','Regrowth Cycle'],            ARRAY['#213997','#fcd142'], '{"va":"humanoid_large","i":{"head":"PLAIN","back":"FIN","marking":"PLAIN","build":"TOWERING","prop":"NONE","scale":1.16}}'::jsonb),
    ('dc-etrigan-the-demon',  'The Cinder Tyrant',        'He was bound to a man who hates him and the feeling is mutual.',                                       ARRAY['Hellfire Breath','Demon Ascent'],            ARRAY['#192571','#fbd71f'], '{"va":"humanoid_large","i":{"head":"HORNS","back":"NONE","marking":"PLAIN","build":"HEAVY","prop":"NONE","scale":1.08}}'::jsonb),
    ('dc-deadman',            'The Quiet Vagrant',        'He is everywhere and nowhere, and he cannot leave until the job is done.',                             ARRAY['Possession Shift','Intangible Pass'],        ARRAY['#1f3a8e','#fbc93d'], '{"i":{"head":"PLAIN","back":"FIN","marking":"PLAIN","build":"SLIGHT","prop":"NONE","scale":0.94}}'::jsonb),
    ('dc-wonder-girl',        'The Bronze Striker',       'She does not yet know how strong she will become, which makes her unpredictable.',                     ARRAY['Lasso Strike','Amazon Rush'],                ARRAY['#23539f','#fba429'], '{"va":"humanoid_large","i":{"head":"PLAIN","back":"NONE","marking":"PLAIN","build":"HEAVY","prop":"SPEAR","scale":1.06}}'::jsonb),
    ('dc-firestorm',          'The Flame Conduit',        'Two minds in one body and they only agree on one thing: the blast.',                                   ARRAY['Transmutation Burst','Fusion Blast'],        ARRAY['#2456a7','#fcba56'], '{"va":"winged","i":{"head":"PLAIN","back":"NONE","marking":"PLAIN","build":"NORMAL","prop":"ORB","scale":1.0}}'::jsonb),
    ('dc-vixen',              'The Storm Vanguard',       'She calls on every animal that ever lived and fights like all of them at once.',                        ARRAY['Totem Strike','Beast Mimicry'],              ARRAY['#222f9b','#fbe12e'], '{"i":{"head":"PLAIN","back":"NONE","marking":"PLAIN","build":"NORMAL","prop":"SPEAR","scale":0.97}}'::jsonb),
    ('dc-captain-cold',       'The Frost Raider',         'He lives by a code because chaos never paid as well.',                                                 ARRAY['Cold Discharge','Outlaw Code'],              ARRAY['#173068','#eda004'], '{"i":{"head":"PLAIN","back":"NONE","marking":"PLAIN","build":"HEAVY","prop":"STAFF","scale":0.99}}'::jsonb),
    ('dc-black-canary',       'The Keen Duelist',         'The cry ends fights — the hands are for when it does not.',                                            ARRAY['Sonic Cry','Brawling Combo'],                ARRAY['#211e8a','#f1f204'], '{"i":{"head":"PLAIN","back":"FIN","marking":"PLAIN","build":"NORMAL","prop":"ORB","scale":0.95}}'::jsonb),
    ('dc-plastic-man',        'The Hollow Bastion',       'He is impossible to hurt because there is nothing solid left to hit.',                                  ARRAY['Elastic Form','Shape Lock'],                 ARRAY['#1c4c82','#fb8e1f'], '{"i":{"head":"PLAIN","back":"NONE","marking":"PLAIN","build":"SQUAT","prop":"NONE","scale":0.96}}'::jsonb),
    ('dc-lobo',               'The Iron Marauder',        'He breaks everything placed in his path and calls what''s left freedom.',                              ARRAY['Savage Fury','Undying Rush'],                ARRAY['#1e1f8a','#fcf756'], '{"va":"humanoid_large","i":{"head":"PLAIN","back":"NONE","marking":"PLAIN","build":"TOWERING","prop":"HAMMER","scale":1.16}}'::jsonb),
    ('dc-wally-west',         'The Scarlet Pioneer',      'He runs until the world slows down and the answers everyone else missed become plain.',                 ARRAY['Force Drain','Infinite Velocity'],           ARRAY['#192471','#fbda1a'], '{"i":{"head":"PLAIN","back":"SHELL","marking":"PLAIN","build":"SLIGHT","prop":"NONE","scale":0.93}}'::jsonb),
    ('dc-kyle-rayner',        'The Cobalt Artisan',       'He is the most creative ring-wielder alive because creativity is all he started with.',               ARRAY['Spectrum Form','Hard Light Array'],          ARRAY['#22379b','#fcdb56'], '{"i":{"head":"PLAIN","back":"SHELL","marking":"PLAIN","build":"NORMAL","prop":"ORB","scale":1.0}}'::jsonb),
    ('dc-azrael',             'The Runed Enforcer',       'The system that built him was designed for war and it worked too well.',                               ARRAY['Conditioned Strike','Flame Blade'],          ARRAY['#255aac','#fcb856'], '{"i":{"head":"HELM","back":"NONE","marking":"PLAIN","build":"HEAVY","prop":"BLADE","scale":1.0}}'::jsonb),
    ('dc-the-atom',           'The Copper Vagrant',       'He shrinks to subatomic and punches at his full weight — the math is devastating.',                    ARRAY['Density Punch','Scale Shift'],               ARRAY['#253fac','#fcd64c'], '{"i":{"head":"PLAIN","back":"NONE","marking":"PLAIN","build":"SLIGHT","prop":"ORB","scale":0.89}}'::jsonb),
    ('dc-animal-man',         'The Feral Catalyst',       'He pulls from the whole animal kingdom at once and the math is overwhelming.',                         ARRAY['Animal Draw','Wild Aura'],                   ARRAY['#1e3c8a','#fbbd29'], '{"i":{"head":"PLAIN","back":"SPINES","marking":"PATCH","build":"NORMAL","prop":"STAFF","scale":0.99}}'::jsonb),
    ('dc-black-lightning',    'The Storm Enforcer',       'He came back to his hometown and decided to fix it himself.',                                          ARRAY['Arc Discharge','Electromagnetic Guard'],    ARRAY['#2538ac','#fbdb33'], '{"i":{"head":"PLAIN","back":"CAPE","marking":"PLAIN","build":"NORMAL","prop":"STAFF","scale":0.99}}'::jsonb),
    ('dc-mister-miracle',     'The Wicked Escapist',      'No trap built by gods or men has held him longer than he allowed.',                                    ARRAY['Phase Vault','Unshackled'],                  ARRAY['#1a4b79','#e86f04'], '{"i":{"head":"PLAIN","back":"CAPE","marking":"PLAIN","build":"NORMAL","prop":"BOW","scale":0.98}}'::jsonb)
)
UPDATE characters c SET
  name         = u.new_name,
  title        = u.new_title,
  universe     = u.new_universe,
  version      = NULL,
  description  = '',
  actor        = NULL,
  abilities    = u.new_abilities,
  palette      = u.new_palette,
  metadata     = u.new_meta,
  category     = 'vigil',
  image_url    = NULL,
  thumbnail_url = NULL,
  image_source  = NULL,
  image_license = NULL,
  image_credit  = NULL,
  wiki_title    = NULL,
  wiki_url      = NULL
FROM vigil_updates u
WHERE c.id = u.id;

-- ────────────────────────────────────────────────────────────────────────────
-- 3. Rename category_ids in rooms and games
-- ────────────────────────────────────────────────────────────────────────────

UPDATE rooms
SET category_ids = array_replace(
      array_replace(category_ids, 'marvel', 'apex'),
      'dc', 'vigil')
WHERE category_ids && ARRAY['marvel','dc'];

UPDATE games
SET category_ids = array_replace(
      array_replace(category_ids, 'marvel', 'apex'),
      'dc', 'vigil')
WHERE category_ids && ARRAY['marvel','dc'];

-- ────────────────────────────────────────────────────────────────────────────
-- 4. Verification
-- ────────────────────────────────────────────────────────────────────────────

DO $$
DECLARE
  apex_count  int;
  vigil_count int;
  old_count   int;
  null_img    int;
BEGIN
  SELECT COUNT(*) INTO apex_count  FROM characters WHERE category = 'apex';
  SELECT COUNT(*) INTO vigil_count FROM characters WHERE category = 'vigil';
  SELECT COUNT(*) INTO old_count   FROM characters WHERE category IN ('marvel','dc');
  SELECT COUNT(*) INTO null_img    FROM characters
    WHERE category IN ('apex','vigil') AND image_url IS NOT NULL;

  ASSERT apex_count  = 60, 'Expected 60 apex rows, got '  || apex_count;
  ASSERT vigil_count = 60, 'Expected 60 vigil rows, got ' || vigil_count;
  ASSERT old_count   = 0,  'Old marvel/dc rows remain: '  || old_count;
  ASSERT null_img    = 0,  'image_url not cleared on '     || null_img || ' rows';

  RAISE NOTICE 'Migration 0042 verified: % apex, % vigil, 0 old, 0 images.',
    apex_count, vigil_count;
END $$;
